const ENCRYPTED_DASHBOARD = "SyAGWFwUVVkWPhQMEERXUhJvR1hWCRRUBz1KXFNdWBdXPhNIXlELFxMkFEFeVU8PVyMIX1cPFAt9bUcREgheUBYpAkMSV1pUBD5aE1NERhgfKAZVV0YUFQQ5Hl1XCRRRHj4XXVNNDBURIQJJCRRcQAQ5DldLGVVaGTkCX0YOFkYHLARUH1ZTQQAoAl8JFFdZHioJHFtAU1gEd0dXXlFOGAQ5BkNGDxZTGygfHEVGV0VNbRBDU0QNFRAsFwsSBQBFD3ZFDzgUFhVXbUcNVl1AC31tRxESFBYVV3EPAAxzYHRXHgRUXFVEXBhtKl5WUVpQBW1bQkJVWBUUIQZCQQkUVxYpAFQQCkAGWX1bHkFEV1tJcUhZAwo8FVdtRxESFBYJB3MuX0ZRRFQUOQ5HVxRGWRY0AENdQVhRVzkIEV9bUlAbYUdSXVlGVAUoSxFTWlIVESIVVFFVRUFXKApBXltPWBIjExFTWlIVMBsmEUFXU1sWPw5eQRoWZg4jBEISR1pcEygVQh4UUkcWKgBQUFhTP1dtRxESFBYVV20AQ1NEXkZbbQZfVhRSUAMsDl1XUBZGFiEGQ0sUVFQZKRQfDhtGC31tRxESFBYJWCkORww+FhVXbUcRDlZDQQMiCRFRWFdGBHBFQltTWBgYOBMcUEBYF1ckAwwQR19SGWAIREYZVEEZb0deXFdaXBQmWhNaVVhRGygrXlVbQ0FfZEURQUBPWRJwRVxTRlFcGWATXkIOFgMHNVwTDGdfUhltKERGCBlXAjkTXlwKPBVXbUcNHVxTVBMoFQ84PhYVV21bVVtCFlYbLBRCDxZaVA4iEkUfQ0RUBz0CQxAKPBVXbUcREghSXAFtBF1TR0UIVSAGWFwZVVoZOQJfRhYIP1dtRxESFBYVSz4CUkZdWVtXLgtQQUcLFxA/DlUfWFdMGDgTEww+FhVXbUcREhQWFUtsShwSZ1VQGSwVWF0UBw9XGg5FWltDQVcKFVBcQBYYWnNtERIUFhVXbUcREghXRwMkBF1XFFVZFj4UDBBXV0cTb1k7EhQWFVdtRxESFBYVSyVVD2FXU1sWPw5eEgUWYh45D15HQBZyBSwJRQ4bXgdJR0cREhQWFVdtRxESFApFSQAIVVdYFkEfKEdTU0dTWR4jAhFRW1tFFiMeEVVGWUIDJUdCUVFYVAUkCB8SdVJfAj4TEVZGV1IQLAVdVxRGWh4jE0ISQFkVBCgTEVRbRFAULBRFEkZTQxIjElQcCBlFSUdtERIUFhVXbUcREhQWCRMkERFRWFdGBHBFQUBRRVADYAVFXEcUC31tRxESFBYVV21HERIUFgkEPQZfEldaVAQ+WhNCRlNGEjlKXVNWU1lVcz5eaxRxRxg6E1kSZERQBCgTQggIGUYHLAkPOBQWFVdtRxESFBYVV21HDVBBQkEYI0dSXlVFRkpvF0NXR1NBWi8TXxAUWVsUIQ5SWQkUVAc9C0hrW29yBSIQRVocEUZGaksRBx0UC0JoWx5QQUJBGCNZOxIUFhVXbUcREhQWFVdtW1NHQEJaGW0EXVNHRQhVPRVUQVFCGBU5CRMSW1hWGyQEWg8WV0UHIR5oXW1xRxg6E1kaE0UEUGFHAAIdFAtGfUINHVZDQQMiCQ84FBYVV21HERIUFhVXbUcNUEFCQRgjR1JeVUVGSm8XQ1dHU0FaLxNfEBRZWxQhDlJZCRRUBz0LSGtbb3IFIhBFWhwRRkZqSxEABB8XSX9XFA4bVEADOQhfDD4WFVdtRxESFBYVV21bHlZdQAt9R0cREhQWFVdtRxESFApRHjtHUl5VRUZKbwRZU0ZCGAQlAl1eFgg/V21HERIUFhVXbUcREhQKRgEqR1hWCRRWHywVRQMWFkMeKBBzXUwLF0dtVxEEBgYVQ31XExJVRFwWYAtQUFFaCFUeBFRcVURcGG1WEVZGV1IQLAVdVxREUAEoCURXFFFHFj0PExJGWVkScEVYX1MUC0tiFEdVCjwVV21HERIUFhVXbUcNHVBfQ0lHbRESFBYVV21HERIUFgkTJBERUVhXRgRwRV1XU1NbE29HWFYJFEYCIApQQE0HF0lxSFVbQgg/fW1HERIUFhVXbUcREghSXAFtBF1TR0UIVT0CXkJYUxgVIh8TDD4WFVdtRxESFBYVV21HEQ5QX0NXLgtQQUcLFwcoCEFeURtBHjkLVBAKc1gHIQhIV1FFFRYjAxFRW0VBV2U0UldaV0ceIkcAGwgZUR47WTsSFBYVV21HERIUFhVXbVtVW0IWVhssFEIPFkZQGD0LVB9dWEUCORQTDD4WFVdtRxESFBYVV21HERIUClEeO0dSXlVFRkpvAVhXWFIXSUdHERIUFhVXbUcREhQWFVdtRxEOWFdXEiFHV11GCxcSIBcAH1ZXRhIhDl9XFgh3Fj4CXVtaUxUSIBddXU1TUARtBF5HWkIJWCEGU1dYCD9XbUcREhQWFVdtRxESFBYVV21bWFxEQ0FXJAMMEFFbRUZgBVBBUVpcGShFEUZNRlBKbwlEX1ZTR1VtClhcCRQEVW0URVdECxdGb0dHU1hDUEpvUgEQCjwVV21HERIUFhVXbUcREhQWCVgpDkcMPhYVV21HERIUFhVXbUcREhQKUR47R1JeVUVGSm8BWFdYUhdJR0cREhQWFVdtRxESFBYVV21HEQ5YV1cSIUdXXUYLFxIgFwAfV1lGA29Zc1NHU1keIwIRUVtFQVcsC10SUVtFGyIeVFdHFh217gwYDhtaVBUoCw84FBYVV21HERIUFhVXbUcREhQWCR4jF0RGFF9RSm8CXEIFG1YYPhMTEkBPRRJwRV9HWVRQBW9HXFtaCxdHb0dCRlFGCFV8RRFEVVpAEnBFAAcEBhdJR0cREhQWFVdtRxESFBYVV21bHlZdQAt9bUcREhQWFVdtRxESFBYVV3EDWEQUVVkWPhQMEFJfUBspRQ84FBYVV21HERIUFhVXbUcREhQWCRssBVReFFBaBXBFVF9EBxgOfEUPDkdGVBltBF1TR0UIVSEFXR9NRBhGb1loAwgZRgcsCQ8SUVtFGyIeVFdHChobLAVUXgo8FVdtRxESFBYVV21HERIUFhVXcQ5fQkFCFR4pWhNXWUYEWjRWExJAT0UScEVfR1lUUAVvR1xbWgsXR29HQkZRRghVfEURRFVaQBJwRQQHFgg/V21HERIUFhVXbUcREhQWFUtiA1hECjwVV21HERIUFhVXbUcREhQWCRMkERFRWFdGBHBFV1tRWlFVc20REhQWFVdtRxESFBYVV21HERIIWlQVKAsRVFtECFUoCkEDGU8HVXNbQkJVWBUUIQZCQQkUWRUhSkhAGQQXSRRVDR1HRlQZc0dUX0RaWg4oAkIOG1pUFSgLDzgUFhVXbUcREhQWFVdtRxESFBYJHiMXREYUX1FKbwJcQgUbTEVvR0VLRFMIVSMSXFBRRBdXIA5fDxYGF1c+E1RCCRQEVW0RUF5BUwhVe1cTDD4WFVdtRxESFBYVV21HERIUChoTJBEPOBQWFVdtRxESFBYVV21HERIIUlwBbQRdU0dFCFUrDlReUBQLfW1HERIUFhVXbUcREhQWFVdtRw1eVVRQG20BXkAJFFAaPVYcSwcUC0s+F1BcFFVZFj4UDBBYVFlaNBUcARYIbERxSEJCVVgLVygKQV5bT1ASPlseXlVUUBtzbRESFBYVV21HERIUFhVXbUcREghfWwc4ExFbUAsXEiAXAB9NBRdXOR5BVwkUWwIgBVRAFhZYHiNaEwIWFkYDKBcMEAUUFQEsC0RXCRQDQm9ZOxIUFhVXbUcREhQWFVdtRxEOG1JcAXNtERIUFhVXbUcREhQWFVdxSFVbQgg/V21HERIUFhVXbUcREhQKUR47R1JeVUVGSm8XVF1EWlBaIAJFQF1VF1ckAwwQUVtFRmAKVEZGX1ZVcyZHV0ZXUhJtBF5BQBZFEj9HVF9EWloOKAILEta2plcxR3BcWkNUG20CXEJYWUwSKEdSXUdCFRU0R0hXVUQPV6/nojgUFhVXbUcREhQWFVdtRw0dUF9DSUdHERIUFhVXbUcREhQKGhMkEQ84PhYVV21HERIUFhVXbVtVW0IWVhssFEIPFkZHGCsORR9WWU1Vc20REhQWFVdtRxESFBYVV3EDWEQ+FhVXbUcREhQWFVdtRxESFEVBDiECDBBQX0YHIQZICBRQWRI1XBFYQUVBHiseHFFbWEESIxMLEkdGVBQoSlNXQEFQEiNcEVNYX1IZYA5FV1lFD1cuAl9GUUQOVyAGQ1VdWBgVIhNFXVkMFUZ5F0kJFFBZEjVKRkBVRg9XOhVQQg8WUhY9XREKRE4OVXNtERIUFhVXbUcREhQWFVdtRw1aBxZGAzQLVA8WW1QFKg5fCBQGDlVzKVRGFEZHGCsORRJHWlwTKBVCDhteBklHRxESFBYVV21HERIUFhVXbVtVW0IWVhssFEIPFkZHEj4CRR9WQlsEb0dCRk1aUEpvClBAU19bWi8IRUZbWw9XfVwTDD4WFVdtRxESFBYVV21HERIUFhVLPhdQXBRVWRY+FAwQRERQBCgTHF5VVFAbb1l8U0ZRXBltN0NXR1NBBHdbHkFEV1tJR0cREhQWFVdtRxESFBYVV21HEQ5WQ0EDIgkRUVhXRgRwRUFAUUVQA2AFRVwWFloZLgtYUV8LFxY9F11LZERaESQTYUBRRVADZUBCAxMaFVp8ThMMGQcQVxkVVFxQChoVOBNFXVoIP1dtRxESFBYVV21HERIUFhVXbVtTR0BCWhltBF1TR0UIVT0VVEFRQhgVOQkTEltYVhskBFoPFldFByEeYUBbUFwDHRVUQVFCHVA+VhYeFAYcVXM0RVNWWlBLYgVERkBZW0lHRxESFBYVV21HERIUFhVXbUcRDlZDQQMiCRFRWFdGBHBFQUBRRVADYAVFXBYWWhkuC1hRXwsXFj0XXUtkRFoRJBNhQFFFUANlQEIDExoVRmRFDxkFExUjPwJfVggZVwI5E15cCjwVV21HERIUFhVXbUcREhQWCVgpDkcMPhYVV21HERIUFhVXbUcRDhtSXAFzbRESFBYVV21HERIUFhVXcQNYRBRVWRY+FAwQRERaESQTHFVGX1FVbQ5VDxZGRxgrDkV1Rl9RRm9ZDR1QX0NJR0cREhQWFVdtRxESFAoaEyQRDzgUFhVXbUcREhQWCVgsFUVbV1pQSUdtERIUFhVXbUcREggXGFptNFJXWldHHiJHAwgUYVwDJUd2QFVYQVdgSg84FBYVV21HERIUFgkWPxNYUVhTFRQhBkJBCRRWFj8DEww+FhVXbUcREhQWFVdtW1kACmVWEiMGQ1tbFgdXGg5FWhRxRxYjEw0dXAQLfW1HERIUFhVXbUcREghGCzoiA1ReFFFHGDoTWRJHQ0UHIhVFV1AWVw5tAENTWkIVETgJVVtaURtXCRVYRFFYFRU0R1VXQFdcGygDEUFVWlQFNEdTU1pSFR8kFVhcUxZTGD8CUlNHQkZZcUhBDD48FVdtRxESFBYVV21HDVZdQBUUIQZCQQkURQUoFFRGGVRBGT5FDzgUFhVXbUcREhQWFVdtRw1BRFdbVy4LUEFHCxcHPwJCV0AbWRYvAl0QCm9aLm0gQ11DQl1XHRVUQVFCRk1xSEJCVVgLfW1HERIUFhVXbUcREhQWCRU4E0VdWhZWGywUQg8WRkcSPgJFH1ZCW1VtCF9RWF9WHHBFUEJEWkwuIj52QFtBQR9lQEIAExoVQmRFDwcRChoVOBNFXVoIP1dtRxESFBYVV21HERIUClcCORNeXBRVWRY+FAwQRERQBCgTHFBAWBdXIglSXl1VXkpvBkFCWE9sGBQgQ11DQl1fahQDFRgWBEdkRQ8DBBMJWC8SRUZbWAt9bUcREhQWFVdtRxESFBYJFTgTRV1aFlYbLBRCDxZGRxI+AkUfVkJbVW0IX1FYX1YccEVQQkRaTC4iPnZAW0FBH2VAQgATGhVFfU4TDAYGEEtiBURGQFlbSUdHERIUFhVXbUcREhQKGhMkEQ84PhYVV21HERIUFhVXbVtVW0IWVhssFEIPFlVdFj8THEFcU1kbb1k7EhQWFVdtRxESFBYVV21bQkRTFlwTcEVSWlVEQUVvR0dbUUF3GDVaEwIUBhVBf1cRBgQGF1csFVhTGVpUFSgLDBBnVVAZLBVYXRQEFRM/BlZVVVRZEm0VVERRWEASbQBDU0ReF1c/CF1XCRRcGipFDw4bRUMQc20REhQWFVdtRxESFBYJWCkORww+PBVXbUcREhQWFVdtRw1WXUAVFCEGQkEJFFkSKgJfVhYWXBNwRUJHWVtUBTRVEwwIGVEeO1k7OBQWFVdtRxESFBYVV3EDWEQUVVkWPhQMEERTWgchAhxQW04XVz4TSF5RCxcTJBRBXlVPD1cvC15RXw0VACQDRVoOFgRHfUIKEAo8FVdtRxESFBYVV21HERIIUlwBbQRdU0dFCFU9Al5CWFMYAyQTXVcWCHAaPQteS1FTRlcsCVUSV1lGA21PYlFRWFQFJAgRAB0KGhMkEQ84PhYVV21HERIUFhVXbUcRDlBfQ1cuC1BBRwsXBygIQV5RG1wZPRJFQRYWRgM0C1QPFltUBSoOXx9WWUEDIgoLEgUARQ92RQ84FBYVV21HERIUFhVXbUcREghSXAFtBF1TR0UIVSsOVF5QFAt9bUcREhQWFVdtRxESFBYVV21HDV5VVFAbbQFeQAkUUBo9VRxQVUVQGyQJVBAKdFQEKAtYXFEWUBo9C15LUVNGVy4IRFxAChobLAVUXgo8FVdtRxESFBYVV21HERIUFhVXcQ5fQkFCFR4pWhNXWUYHWi8GQldYX1sSb0dFS0RTCFUjElxQUUQXVyAOXw8WBxdXPhNUQgkUBFVtEVBeQVMIVXhXExJQX0YWLwtUVj4WFVdtRxESFBYVV21HERIUFhVXbRRFS1hTCFUvBlJZU0RaAiMDCxIXUFQRLAEICRRUWgUpAkMfV1lZGD9dEUZGV1sEPQZDV1pCDlVzbRESFBYVV21HERIUFhVXbUcNHVBfQ0lHRxESFBYVV21HERIUFhVXbVtVW0IWVhssFEIPFlBcEiEDEww+FhVXbUcREhQWFVdtRxESFBYVSyEGU1dYFlMYP1oTV1lGB1ouCEJGFghhGDkGXRJHV1kWPx4RUVtFQVdlpZJZHQoaGywFVF4KPBVXbUcREhQWFVdtRxESFBYVV3EOX0JBQhUeKVoTV1lGB1ouCEJGFhZBDj0CDBBaQ1gVKBUTEllfW0pvVxMSR0JQB3BFABAUQFQbOAIMEAUDBUdvR1VbR1dXGygDOxIUFhVXbUcREhQWFVdtRxESFBYVBDkeXVcJFFcWLgxWQFtDWxN3RxJUVVBUEXRcEVBbRFESP0pSXVhZR01tE0NTWkVFFj8CX0YPFAt9bUcREhQWFVdtRxESFBYVV3FIVVtCCD9XbUcREhQWFVdtRxESFBYVSykORxJXWlQEPloTVF1TWRNvWTsSFBYVV21HERIUFhVXbUcREhQKWRYvAl0SUllHSm8CXEIGG0xGb1kNQURXW1cuC1BBRwsXGy8LHEtGGwRVcz4ADhtFRRYjWRFXWUZZGDQCVEEIGVkWLwJdDD4WFVdtRxESFBYVV21HERIUFhVLJAlBR0AWXBNwRVRfRAQYDnxFEUZNRlBKbwlEX1ZTR1VtClhcCRQFVW0URVdECxdGb0dHU1hDUEpvUgQQCjwVV21HERIUFhVXbUcREhQWCVgpDkcMPhYVV21HERIUFhVXbUcREhQKUR47R1JeVUVGSm8BWFdYUhdJR0cREhQWFVdtRxESFBYVV21HEQ5YV1cSIUdXXUYLFxIgFwMfTQQXSXEUQVNaFlYbLBRCDxZaVxtgHkMfBhQLLn9bHkFEV1tJbQJcQlhZTBIoFA0dWFdXEiFZOxIUFhVXbUcREhQWFVdtRxESFApcGT0SRRJdUghVKApBABlPB1VtE0hCUQsXGTgKU1dGFBUaJAkMEAQUFQQ5AkEPFgcXVzsGXUdRCxdBfUUPOBQWFVdtRxESFBYVV21HERIIGVEeO1k7EhQWFVdtRxESFBYVV21HEQ5QX0NXLgtQQUcLFxEkAl1WFgg/V21HERIUFhVXbUcREhQWFVdtW11TVlNZVysIQw8WU1gHf0pIARYICQQ9Bl8SV1pUBD5aE15WWhgOP0oCEApvBktiFEFTWggVEiAXXV1NU1AEcUhdU1ZTWUlHRxESFBYVV21HERIUFhVXbUcRDl1YRQI5R1hWCRRQGj1VHEsHFBUDNBdUDxZYQBovAkMQFFtcGXBFARAURUESPVoTAxYWQxYhElQPFgAAVXNtERIUFhVXbUcREhQWFVdtRw0dUF9DSUdHERIUFhVXbUcREhQWFUtiA1hECjw/V21HERIUFhVXbUcREhQKUR47R0JGTVpQSm8BXlxAG0ISJABZRg4WA0d9XBFUW1hBWj4OS1cOFgVZdV9DV1kNFRQiC15ADhZDFj9PHB9AU00DZFwRX1VEUh4jSkVdRAwVTz0fChAKfFoVbSRDV1VCXBgjR1BcUDwVV21HERIUFhVXbUcREhQWYAc+DFheWF9bEG0hXkBRVVQEOVseVl1AC31tRxESFBYVV21HERIUFgkDLAVdVxRVWRY+FAwQUllHEi4GQkYZQlQVIQITDD4WFVdtRxESFBYVV21HERIUCkEfKAZVDD4WFVdtRxESFBYVV21HERIUFhVLORUPOBQWFVdtRxESFBYVV21HERIUFhVXcRNZDHlTQQUkBA0dQF4LfW1HERIUFhVXbUcREhQWFVdtRxESCEJdVy4LUEFHCxcUIgscS0YbBFVzPgAOG0JdSUdHERIUFhVXbUcREhQWFVdtRxESFApBH20EXVNHRQhVLghdH01EGEVvWWgACBlBH3NtERIUFhVXbUcREhQWFVdtRxESFBYJAyVHUl5VRUZKbwReXhlPR1p+RQ9rBwoaAyVZOxIUFhVXbUcREhQWFVdtRxESFBYVSzkPD2ZbQlQbcUhFWgo8FVdtRxESFBYVV21HERIUFhVXcUhFQAo8FVdtRxESFBYVV21HERIUFglYOQ9UU1AIP1dtRxESFBYVV21HERIUFhVLOQVeVk0IP1dtRxESFBYVV21HERIUFhVXbVtFQAo8FVdtRxESFBYVV21HERIUFhVXbUcNRlAIexI6R1tdVkUVFD8CUEZRUhVfCzN0GwgZQRNzbRESFBYVV21HERIUFhVXbUcREhQWCQMpR1hWCRRTGD8CUlNHQhgZKBAcSwUUFRQhBkJBCRRHEiwDHF1aWkxaOwZdEAoGCVg5Aw84FBYVV21HERIUFhVXbUcREhQWFVdxE1USXVIIVSsIQ1dXV0YDYAlURRlPB1VtBF1TR0UIVT8CUFYZWVsbNEpHU1gUC0dxSEVWCjwVV21HERIUFhVXbUcREhQWFVdtRw1GUBZcE3BFV11GU1YWPhMcXFFBGA5+RRFRWFdGBHBFQ1dVUhgYIwtIH0JXWVVzVw0dQFILfW1HERIUFhVXbUcREhQWFVdtRxESCEJRVyQDDBBSWUcSLgZCRhlYUABgE15GVVoXVy4LUEFHCxcFKAZVH1tYWQ5gEVBeFggFS2ITVQw+FhVXbUcREhQWFVdtRxESFBYVS2ITQww+FhVXbUcREhQWFVdtRxESFBYVSzkVDzgUFhVXbUcREhQWFVdtRxESFBYVV3ETVQx+WVcEbRJBQV9fWRsoAxEacmJwXnFIRVYKPBVXbUcREhQWFVdtRxESFBYVV21HDUZQCAkeIxdERhRCTAcoWhNcQVtXEj9FEVtQCxcCPRRaW1haUBNgHgAQFFtcGXBFARAUQFQbOAIMEAYUC0tiE1UMPhYVV21HERIUFhVXbUcREhQWFVdtW0VWCgpcGT0SRRJAT0UScEVfR1lUUAVvR1hWCRRABz4MWF5YU1FaNFUTEllfW0pvVxMSQldZAihaEwYWCAlYOQMPOBQWFVdtRxESFBYVV21HERIUFhVXcRNVDAhfWwc4ExFGTUZQSm8JRF9WU0dVbQ5VDxZDRQQmDl1eUVIYDn5FEV9dWAhVfUURRFVaQBJwRQQQCgoaAylZOxIUFhVXbUcREhQWFVdtRxESFBYVSzkDEVtQCxcCPRRaW1haUBNgE15GVVoXVz4TSF5RCxcRIglFH0NTXBAlEwsSAgYFTG0EXl5bRA9XOwZDGhkbVBQuAl9GHQ0XSXxWDR1AUgt9bUcREhQWFVdtRxESFBYVV21HDR1ARAt9bUcREhQWFVdtRxESFBYVV21HDUZGCD9XbUcREhQWFVdtRxESFBYVV21HEQ5AUgskJg5dXkcWVBQ8ElhAUVIVGSITVEEIGUETc20REhQWFVdtRxESFBYVV21HERIUFgkDKVkNW1pGQANtE0hCUQsXAygfRRAUX1FKbxRaW1haRlojCEVXGU8EVW0RUF5BUwhVDiZ1EmBEVB4jDl9VFhZFGywEVFpbWlESP1oTVxpRG1cZFVBbWl9bEG9ZDR1AUgt9bUcREhQWFVdtRxESFBYVV21HERIIQlFJcQ5fQkFCFQM0F1QPFkJQDzlFEVtQCxcEJg5dXkcbWxg5AhxLBhQVASwLRFcJFHQgHkdyXltDUVcOAkNGRxQ/V21HERIUFhVXbUcREhQWFVdtRxESFBYVByEGUldcWVkTKBUMEFEYUlltJFRAQF9THi4GRVtbWEZVc1seRlAIP1dtRxESFBYVV21HERIUFhVXbUcRDkBSC0skCUFHQBZBDj0CDBBAU00Db0dYVgkURhwkC11BGVhaAyhKSAEWFkMWIRJUDxZ7cCRtNF5UQEFUBShHdGBkFD9XbUcREhQWFVdtRxESFBYVV21HERIUFhUHIQZSV1xZWRMoFQwQURhSWW00XlRAQVQFKEdiS0dCUBo+RQ8OG0JRSUdHERIUFhVXbUcREhQWFVdtRxESFApBE3NKDR1AUgt9bUcREhQWFVdtRxESFBYVV21HDR1ARAt9bUcREhQWFVdtRxESFBYVV3FIRVBbUkxJR0cREhQWFVdtRxESFBYVS2ITUFBYUwt9R0cREhQWFVdtRxESFBYVSykORxJHQkwbKFoTVFtYQVo6AlhVXEIPV3tXAQkUUFoZOUpCW05TD1d9SQkKRlNYTG0EXl5bRA9XOwZDGhkbQRI1ExgJFFtUBSoOXx9AWUVNbVYHQkwNF0keBl1TRk8VNSwJVUEUWVN9bUcREhQWFVdtRxESFBYVVwMCRhJ+WVcEbSRDV1VCUBNiNFBEUVIJWCkORww+FhVXbUcREhQWFVdtRxEOQFdXGyhHUl5VRUZKbwVQXFBFGAMsBV1XFgg/V21HERIUFhVXbUcREhQWFUs5D1RTUAg/V21HERIUFhVXbUcREhQWFVdtW0VACjwVV21HERIUFhVXbUcREhQWFVdtRw1GXAhmFiEGQ0sUdFQZKVseRlwIP1dtRxESFBYVV21HERIUFhVXbUcRDkBeFRQhBkJBCRRWGCFKSEAZBxdJFFYNHUBeC31tRxESFBYVV21HERIUFhVXbUcREghCXVcuC1BBRwsXFCILHEtGGwdVcz4DDhtCXUlHRxESFBYVV21HERIUFhVXbUcREhQKQR9tBF1TR0UIVS4IXR9NRBhEb1loAQgZQR9zbRESFBYVV21HERIUFhVXbUcREhQWCQMlWWVdQFdZBHFIRVoKPBVXbUcREhQWFVdtRxESFBYVV3FIRUAKPBVXbUcREhQWFVdtRxESFBYJWDkPVFNQCD9XbUcREhQWFVdtRxESFBYVSzkFXlZNCD9XbUcREhQWFVdtRxESFBYVV21bRUAKPBVXbUcREhQWFVdtRxESFBYVV21HDUZQCHkSPhQRRlxXW1ePxAAHGA4FR21bQl9VWllXPhNIXlELFxMkFEFeVU8PFSEIUlkPVVobIhULRFVEHVpgCkRGUVIcTCsIX0YZQVAeKg9FCFpZRxosCwoQCh5jFiESVFYUV0F9bUcREhQWFVdtRxESFBYVV21HERIUFhVXj8QAB18fCVg+ClBeWAgJWDkDDzgUFhVXbUcREhQWFVdtRxESFBYVV3ETVQwIX1sHOBMRRk1GUEpvCURfVlNHVW0EXVNHRQhVLwZfVhlfWwc4ExMSUFdBFmAFUFxQCxdHb0dVU0BXGA4oBkMfXVJNSm9WExJZX1tKb1cTEkJXWQIoWhMCFggJWDkDDzgUFhVXbUcREhQWFVdtRxESFBYVV3ETVQwIX1sHOBMRRk1GUEpvCURfVlNHVW0EXVNHRQhVLwZfVhlfWwc4ExMSUFdBFmAFUFxQCxdHb0dVU0BXGA4oBkMfXVJNSm9VExJZX1tKb1cTEkJXWQIoWhMCFggJWDkDDzgUFhVXbUcREhQWFVdtRxESFBYVV3ETVQwIX1sHOBMRRk1GUEpvCURfVlNHVW0EXVNHRQhVLwZfVhlfWwc4ExMSUFdBFmAFUFxQCxdHb0dVU0BXGA4oBkMfXVJNSm9UExJZX1tKb1cTEkJXWQIoWhMCFggJWDkDDzgUFhVXbUcREhQWFVdtRxESFBYVV3ETVRJXWlQEPloTUFVYUVo/CEYfQFlBFiFFEVtQCxcVLAlVH0BZQRYhSgEQCgYJWDkDDzgUFhVXbUcREhQWFVdtRxESFBYJWDkVDzgUFhVXbUcREhQWFVdtRxESFBYJAz9ZOxIUFhVXbUcREhQWFVdtRxESFBYVSzkDD/CXBwBbdVcAEhkW99R/Uh0CBAYVSz4KUF5YFkYDNAtUDxZSXAQ9C1BLDlRZGC4MClFbWloFdxFQQBwbGBo4E1RWHQ1TGCMTHEVRX1IfOV1fXUZbVBt2RQ8aYldZAigDEVNAPBVXbUcREhQWFVdtRxESFBYVV21HERIUFvfUf1cfBl8fCVg+ClBeWAgJWDkDDzgUFhVXbUcREhQWFVdtRxESFBYVV3ETVQwIX1sHOBMRRk1GUEpvCURfVlNHVW0EXVNHRQhVLwZfVhlfWwc4ExMSUFdBFmAFUFxQCxdGb0dVU0BXGA4oBkMfXVJNSm9WExJZX1tKb1cTEkJXWQIoWhMCFggJWDkDDzgUFhVXbUcREhQWFVdtRxESFBYVV3ETVQwIX1sHOBMRRk1GUEpvCURfVlNHVW0EXVNHRQhVLwZfVhlfWwc4ExMSUFdBFmAFUFxQCxdGb0dVU0BXGA4oBkMfXVJNSm9VExJZX1tKb1cTEkJXWQIoWhMCFggJWDkDDzgUFhVXbUcREhQWFVdtRxESFBYVV3ETVQwIX1sHOBMRRk1GUEpvCURfVlNHVW0EXVNHRQhVLwZfVhlfWwc4ExMSUFdBFmAFUFxQCxdGb0dVU0BXGA4oBkMfXVJNSm9UExJZX1tKb1cTEkJXWQIoWhMCFggJWDkDDzgUFhVXbUcREhQWFVdtRxESFBYVV3ETVRJXWlQEPloTUFVYUVo/CEYfQFlBFiFFEVtQCxcVLAlVH0BZQRYhSgAQCgYJWDkDDzgUFhVXbUcREhQWFVdtRxESFBYJWDkVDzgUFhVXbUcREhQWFVdtRxESFBYJAz9ZOxIUFhVXbUcREhQWFVdtRxESFBYVSzkDD/CXBABbfVcAEhkW99R+Uh0CBAYVSz4KUF5YFkYDNAtUDxZSXAQ9C1BLDlRZGC4MClFbWloFdxFQQBwbGBo4E1RWHQ1TGCMTHEVRX1IfOV1fXUZbVBt2RQ8aYldZAigDEVNAPBVXbUcREhQWFVdtRxESFBYVV21HERIUFvfUfldaGwgZRhosC10MCBlBE3NtERIUFhVXbUcREhQWFVdtRxESFBYJAylZDVtaRkADbRNIQlELFxk4ClNXRhQVFCEGQkEJFFcWIwMcW1pGQANvR1VTQFcYFSwJVQ8WBBdXKQZFUxlPUBY/SlhWTAsXRm9HXFtaCxdHb0dHU1hDUEpvUhMMCBlBE3NtERIUFhVXbUcREhQWFVdtRxESFBYJAylZDVtaRkADbRNIQlELFxk4ClNXRhQVFCEGQkEJFFcWIwMcW1pGQANvR1VTQFcYFSwJVQ8WBBdXKQZFUxlPUBY/SlhWTAsXRW9HXFtaCxdHb0dHU1hDUEpvVBMMCBlBE3NtERIUFhVXbUcREhQWFVdtRxESFBYJAylZDVtaRkADbRNIQlELFxk4ClNXRhQVFCEGQkEJFFcWIwMcW1pGQANvR1VTQFcYFSwJVQ8WBBdXKQZFUxlPUBY/SlhWTAsXRG9HXFtaCxdHb0dHU1hDUEpvVRMMCBlBE3NtERIUFhVXbUcREhQWFVdtRxESFBYJAylHUl5VRUZKbwVQXFAbRxg6SkVdQFdZVW0OVQ8WVFQZKUpFXUBXWVp/RQ8DBAoaAylZOxIUFhVXbUcREhQWFVdtRxESFAoaAz9ZOxIUFhVXbUcREhQWFVdtRxESFApBBXNtERIUFhVXbUcREhQWFVdtRxESFBYJAylZ85EHAxlHfVYRHxT0lkN4SwECBBYJBCAGXV4URUEOIQIMEFBfRgchBkgIVlpaFCZcUl1YWUdNOwZDGhkbWAI5AlUbD1BaGTlKRlddUV0DdwleQFlXWUxvWRlkVVpAEilHUEY+FhVXbUcREhQWFVdtRxESFBYVV21HERIU9JZDfQwYDhtFWBYhCw8OG0JRSUdHERIUFhVXbUcREhQWFVdtRxESFApBE3NbWFxEQ0FXOR5BVwkUWwIgBVRAFhZWGywUQg8WVFQZKUpYXERDQVVtA1BGVRtXFiMDDBAHFBUTLBNQH01TVAVgDlVKCRQEVW0KWFwJFAVVbRFQXkFTCFV9RQ8OG0JRSUdHERIUFhVXbUcREhQWFVdtRxESFApBE3NbWFxEQ0FXOR5BVwkUWwIgBVRAFhZWGywUQg8WVFQZKUpYXERDQVVtA1BGVRtXFiMDDBAHFBUTLBNQH01TVAVgDlVKCRQHVW0KWFwJFAVVbRFQXkFTCFV/RQ8OG0JRSUdHERIUFhVXbUcREhQWFVdtRxESFApBE3NbWFxEQ0FXOR5BVwkUWwIgBVRAFhZWGywUQg8WVFQZKUpYXERDQVVtA1BGVRtXFiMDDBAHFBUTLBNQH01TVAVgDlVKCRQGVW0KWFwJFAVVbRFQXkFTCFV/RQ8OG0JRSUdHERIUFhVXbUcREhQWFVdtRxESFApBE20EXVNHRQhVLwZfVhlEWgBgE15GVVoXVyQDDBBWV1sTYBNeRlVaGERvWQUOG0JRSUdHERIUFhVXbUcREhQWFVdtRxEOG0JHSUdHERIUFhVXbUcREhQWFVdtRxEOQEQLfW1HERIUFhVXbUcREhQWFVdtRxESCEJRSY/EBQcYBgVGbUoR8JcDAFt9VwESCEVYFiELEUFAT1kScEVVW0dGWRY0XVNeW1VeTC4IXV1GDEMWP08cH1lDQRIpTgpUW1hBWjoCWFVcQg8ZIhVcU1gNF0llMVBeQVNRVywTOxIUFhVXbUcREhQWFVdtRxESFBYVV21HEfCXAwUcZFseQVlXWRtzWx5GUAg/V21HERIUFhVXbUcREhQWFVdtRxEOQFILSyQJQUdAFkEOPQIMEFpDWBUoFRMSV1pUBD5aE1BVWFFaJAlBR0AUFRMsE1AfVldbE3BFBRAUUlQDLEpIV1VEGB4pHwwQBRQVGiQJDBAEFBUBLAtEVwkUBVVzWx5GUAg/V21HERIUFhVXbUcREhQWFVdtRxEOQFILSyQJQUdAFkEOPQIMEFpDWBUoFRMSV1pUBD5aE1BVWFFaJAlBR0AUFRMsE1AfVldbE3BFBRAUUlQDLEpIV1VEGB4pHwwQBhQVGiQJDBAEFBUBLAtEVwkUBVVzWx5GUAg/V21HERIUFhVXbUcREhQWFVdtRxEOQFILSyQJQUdAFkEOPQIMEFpDWBUoFRMSV1pUBD5aE1BVWFFaJAlBR0AUFRMsE1AfVldbE3BFBRAUUlQDLEpIV1VEGB4pHwwQBxQVGiQJDBAEFBUBLAtEVwkUBFVzWx5GUAg/V21HERIUFhVXbUcREhQWFVdtRxEOQFIVFCEGQkEJFFcWIwMcQFtBGAMiE1BeFhZcE3BFU1NaUhgDIhNQXhkCF0l8Wx5GUAg/V21HERIUFhVXbUcREhQWFVdtWx5GRgg/V21HERIUFhVXbUcREhQWFVdtW0VACjwVV21HERIUFhVXbUcREhQWFVdtRw1GUAj31HhSHQIEBh5XcRRcU1haFQQ5Hl1XCRRRHj4XXVNNDFcbIgRaCVdZWRg/XUdTRh4YWiASRVdQHw4RIglFH0NTXBAlEwtcW0RYFiFcEwwcYFQbOAJVElVCP1dtRxESFBYVV21HERIUFhVXbUcREhQWFbXuUQRZHQoaBCAGXV4KChoDKVk7EhQWFVdtRxESFBYVV21HERIUFhVLOQMPDl1YRQI5R0VLRFMIVSMSXFBRRBdXLgtQQUcLFxUsCVUfXVhFAjlFEVZVQlRaLwZfVgkUAFVtA1BGVRtMEiwVHFtQTghVfEURX11YCFV9RRFEVVpAEnBFARAKChoDKVk7EhQWFVdtRxESFBYVV21HERIUFhVLOQMPDl1YRQI5R0VLRFMIVSMSXFBRRBdXLgtQQUcLFxUsCVUfXVhFAjlFEVZVQlRaLwZfVgkUAFVtA1BGVRtMEiwVHFtQTghVf0URX11YCFV9RRFEVVpAEnBFARAKChoDKVk7EhQWFVdtRxESFBYVV21HERIUFhVLOQMPDl1YRQI5R0VLRFMIVSMSXFBRRBdXLgtQQUcLFxUsCVUfXVhFAjlFEVZVQlRaLwZfVgkUAFVtA1BGVRtMEiwVHFtQTghVfkURX11YCFV9RRFEVVpAEnBFARAKChoDKVk7EhQWFVdtRxESFBYVV21HERIUFhVLOQMRUVhXRgRwRVNTWlIYBSIQHEZbQlQbb0dYVgkUVxYjAxxGW0JUG2BSEwwEChoDKVk7EhQWFVdtRxESFBYVV21HERIUChoDP1k7EhQWFVdtRxESFBYVV21HERIUCkEFbQRdU0dFCFU5CEVTWBtHGDpFDzgUFhVXbUcREhQWFVdtRxESFBYVV3ETVQxgWUEWIRQNHUBSC31tRxESFBYVV21HERIUFhVXbUcREghCUVckAwwQVldbE2AEXl4ZQloDLAscSwUUC0JxSEVWCjwVV21HERIUFhVXbUcREhQWFVdtRw1GUBZcE3BFU1NaUhgUIgscRltCVBtgHgMQCgMJWDkDDzgUFhVXbUcREhQWFVdtRxESFBYVV3ETVRJdUghVLwZfVhlVWhtgE15GVVoYDn5FDwcIGUETc20REhQWFVdtRxESFBYVV21HERIUFgkDKUdYVgkUVxYjAxxVRldbE2ATXkZVWhdJfFINHUBSC31tRxESFBYVV21HERIUFhVXbUcNHUBEC31tRxESFBYVV21HERIUFhVXcUhFUFtSTElHRxESFBYVV21HERIUFhVLYhNQUFhTC31HRxESFBYVV21HERIUFhVLKQ5HEldaVAQ+WhNCUVlFGyhKXFdARFwUb0dYVgkUUBo9VRxfUUJHHi5FOxIUFhVXbUcREhQWFVdtRxFBQE9ZEnBFXFNGUVwZYBNeQg4WBEM9HwoSRFdREyQJVggUBwcHNVwRUFVVXhA/CERcUAwVVCsGV1NSDw5XLwhDVlFEGAUsA1hHRwwVTz0fChJWWUcTKBULEgVGTVc+CF1bUBZDFj9PHB9WWUcTKBUYCRRaXBkoSllXXVFdA3dHABwADRdJR0cREhQWFVdtRxESFBYVV20vVFNQVVoCIxMLEnZXRhJtUgEeFG8ETW1SBB4UbwdNbVEBHhRvBk1tUQQ4FBYVV21HERIUFhVXbUcNHVBfQ0lHRxESFBYVV21HERIUChoTJBEPOD4WFVdtRxESFBYVV21bVVtCFlYbLBRCDxZGRxgrDkUfVllNVXNtERIUFhVXbUcREhQWFVdxA1hEPhYVV21HERIUFhVXbUcREhRFQQ4hAgwQUF9GByEGSAgUUFkSNVwRWEFFQR4rHhxRW1hBEiMTCxJHRlQUKEpTV0BBUBIjXBFTWF9SGWAORVdZRQ9XLgJfRlFEDlcgBkNVXVgYFSITRV1ZDBVGeRdJCRRQWRI1SkZAVUYPVzoVUEIPFlIWPV0RCkRODlVzbRESFBYVV21HERIUFhVXbUcNWgcWRgM0C1QPFltUBSoOXwgUBg5VcylURhRGRxgrDkUSR1pcEygVQg4bXgZJR0cREhQWFVdtRxESFBYVV21bVVtCFlYbLBRCDxZGRxI+AkUfVkJbBG9HQkZNWlBKbwpQQFNfW1ovCEVGW1sPV31cEww+FhVXbUcREhQWFVdtRxESFBYVSz4XUFwUVVkWPhQMEEREUAQoExxeVVRQG29ZfFNGUVwZbTdDV0dTQQR3Wx5BRFdbSUdHERIUFhVXbUcREhQWFVdtRxEOVkNBAyIJEVFYV0YEcEVBQFFFUANgBUVcFhZaGS4LWFFfCxcWPRddS2REWhEkE2FAUUVQA2VAQgATGhVafE4TDBkHEFcZFVRcUAoaFTgTRV1aCD9XbUcREhQWFVdtRxESFBYVV21bU0dAQloZbQRdU0dFCFU9FVRBUUIYFTkJExJbWFYbJARaDxZXRQchHmFAW1BcAx0VVEFRQh1QPlUWHhQGHFVzNEVTVlpQS2IFREZAWVtJR0cREhQWFVdtRxESFBYVV21HEQ5WQ0EDIgkRUVhXRgRwRUFAUUVQA2AFRVwWFloZLgtYUV8LFxY9F11LZERaESQTYUBRRVADZUBCABMaFUZkRQ8ZBRMVIz8CX1YIGVcCORNeXAo8FVdtRxESFBYVV21HERIUFglYKQ5HDD4WFVdtRxESFBYVV21HEQ4bUlwBc20REhQWFVdtRxESFBYVV3EDWEQUVVkWPhQMEEREWhEkExxVRl9RVW0OVQ8WRkcYKw5FdUZfUUVvWQ0dUF9DSUdHERIUFhVXbUcREhQKGhMkEQ84FBYVV21HERIUFglYLBVFW1daUElHRxESFBYVV21bHkFRVUEeIgkPOBQWFVdtRw0dUF9DSUdtERIUFhVXcUYcHxRkXBAlExFhQVtYFj8eEWJVWFAbbUocDD4WFVdtRxEOVUVcEyhHUl5VRUZKbxRYVlFUVAVvWTsSFBYVV21HEQ5HU1YDJAhfEldaVAQ+WhNBQVtYFj8eHEFRVUEeIgkTEkdCTBsoWhNfVURSHiNKRV1EDBVHdkUPOBQWFVdtRxESFBYJEyQROxIUFhVXbUcREhQWFQQ5Hl1XCRRRHj4XXVNNDBURIQJJCRRcQAQ5DldLGVVaGTkCX0YOFkYHLARUH1ZTQQAoAl8JFFdZHioJHFtAU1gEd0dSV1pCUAV2R1xTRlFcGWAFXkZAWVhNbVYDQkwNFRAsFwsSDEZNTG0BXVdMG0IFLBcLEkNEVAd2RQ84FBYVV21HERIUFhVXcQ8DEkdCTBsoWhNfVURSHiNdEQIPFlMYIxMcQV1MUE1tVkNXWQ0XSR4SXF9VRExXIAJFQF1VRktiDwMMPhYVV21HERIUFhVXbVtVW0IWRgM0C1QPFlJcBD0LUEsOFlMbKB8KElNXRU1tX0FKDxZUGyQAXx9dQlAaPl0RUVFYQRI/XBMMPhYVV21HERIUFhVXbUcRDlZDQQMiCRFbUAsXEikORR9WV0YSIQ5fVxlUQRlvR1JeVUVGSm8XQ1dHU0FaLxNfEBRFQQ4hAgwQWVdHECQJHFBbQkEYIF0RAg8UCzIpDkUSdldGEiEOX1cIGVcCORNeXAo8FVdtRxESFBYVV21HERIIVEADOQhfEl1SCFUkCkFdRkIYFTkJExJXWlQEPloTQkZTRhI5SlNGWhQVBDkeXVcJFFgWPwBYXBlUWgM5CFwIFAYOVXMuXEJbREFLYgVERkBZW0lHRxESFBYVV21HERIUFhVLLxJFRltYFR4pWhNXTEZaBTlKU0ZaFD9XbUcREhQWFVdtRxESFBYVBDkeXVcJFFcWLgxWQFtDWxN3R0dTRh4YWiwEUldaQhxMbQReXltED1c6D1hGUQ0VFSIVVVdGDBUZIglUCRRGVBMpDl9VDhYDBzVHAABETg5XLwhDVlFEGAUsA1hHRwwVTz0fChJSWVsDYBBUW1NeQU1tUQECDxZWAj8UXkAOFkUYJAlFV0YNFREiCUUfR19PEndHARwMRFAadkdFQFVYRh45Dl5cDhZaBywEWEZNFgVZfxQKEApzTQciFUUOG1RAAzkIXww+FhVXbUcREhQWFVdtRxEOXVhFAjlHRUtEUwhVKw5dVxYWXBNwRVhfRFlHA2ABWF5RG1wZPRJFEBRXVhQoF0UPFhhWBDtFEUFAT1kScEVVW0dGWRY0XRFcW1hQTG9ZOxIUFhVXbUcREhQWFUtiA1hECjwVV21HERIUFhVXcUhVW0IIP31tRxESFBYVV21HDUZVVFkSbQRdU0dFCFU+ElxfVURMWjkGU15RFBUeKVoTQUFbWBY/HmVTVlpQVXNtERIUFhVXbUcREhQWCQMvCFVLCjwVV21HERIUFhVXbUcREghCR0lHRxESFBYVV21HERIUFhVXbVtFVgplVhIjBkNbWxYES2ITVQw+FhVXbUcREhQWFVdtRxESFApBE3MlUEFRChoDKVk7EhQWFVdtRxESFBYVV21HEQ5AUhUUIQZCQQkUVhghSkhAGQcXSRRWDR1AUgt9bUcREhQWFVdtRxESFBYVV3ETVRJXWlQEPloTUVtaGA4/SgMQCm8HS2ITVQw+FhVXbUcREhQWFVdtRxESFApBE20EXVNHRQhVLghdH01EGERvWWgBCBlBE3NtERIUFhVXbUcREhQWFVdxSEVACjwVV21HERIUFhVXbUcREghCR0lHRxESFBYVV21HERIUFhVXbVtFVgp3Wxk4Bl0SUVtFGyIeVFcUVVoEOVseRlAIP1dtRxESFBYVV21HERIUFhVLOQMRW1ALFwR8SlRfRBtXFj4CXVtaUxdJr+eiDhtCUUlHRxESFBYVV21HERIUFhVXbVtFVhRfUUpvFAAfUVtFWjRWEwzWtqZLYhNVDD4WFVdtRxESFBYVV21HERIUCkETbQ5VDxZFBFooCkEfTQQXSa/nog4bQlFJR0cREhQWFVdtRxESFBYVV21bRVYUX1FKbxQAH1FbRVo0VBMM1ramS2ITVQw+FhVXbUcREhQWFVdtRxEOG0JHSUdHERIUFhVXbUcREhQWFUs5FQ84FBYVV21HERIUFhVXbUcREghCUUkDAkUSRERaESQTEURVWkAScUhFVgo8FVdtRxESFBYVV21HERIUFgkDKUdYVgkURkZgF0NdUhtXFj4CXVtaUxdJr+eiDhtCUUlHRxESFBYVV21HERIUFhVXbVtFVhRfUUpvFAAfRERaEWAeABAK1LXkcUhFVgo8FVdtRxESFBYVV21HERIUFgkDKUdYVgkURkZgF0NdUhtMRW9Z07KnChoDKVk7EhQWFVdtRxESFBYVV21HEQ5AUhUeKVoTQQUbRQUiARxLBxQLlc30DR1AUgt9bUcREhQWFVdtRxESFBYJWDkVDzgUFhVXbUcREhQWFVdtRw1GRgg/V21HERIUFhVXbUcREhQWFUs5Aw9hV1NbFj8OXhIGChoDKVk7EhQWFVdtRxESFBYVV21HEQ5AUgs1LBRUDhtCUUlHRxESFBYVV21HERIUFhVXbVtFVhRVWRY+FAwQV1lZWjQVHAMWCGxGcUhFVgo8FVdtRxESFBYVV21HERIUFgkDKUdSXlVFRkpvBF5eGU9HWn9FD2sGChoDKVk7EhQWFVdtRxESFBYVV21HEQ5AUhUUIQZCQQkUVhghSkhAGQUXSRRUDR1AUgt9bUcREhQWFVdtRxESFBYJWDkVDzgUFhVXbUcREhQWFVdtRw1GRgg/V21HERIUFhVXbUcREhQWFUs5Aw9zWlhAFiFHVF9EWloOKAIRUVtFQUtiE1UMPhYVV21HERIUFhVXbUcREhQKQRNtDlUPFkUHWigKQR9WV0YSIQ5fVxYI1/feWx5GUAg/V21HERIUFhVXbUcREhQWFUs5AxFbUAsXBH9KVF9EG0xGb1nTsqcKGgMpWTsSFBYVV21HERIUFhVXbUcRDkBSFR4pWhNBBhtQGj1KSAAWCNf33lseRlAIP1dtRxESFBYVV21HERIUFhVLOQMRW1ALFwR/SlRfRBtMRG9Z07KnChoDKVk7EhQWFVdtRxESFBYVV21bHkZGCD9XbUcREhQWFVdtRxESFApBBXNtERIUFhVXbUcREhQWFVdtRw1GUAh7EjlHQUBbUFwDbRFQXkFTCVg5Aw84FBYVV21HERIUFhVXbUcREghCUVckAwwQRwQYBz8IVx9WV0YSIQ5fVxYI1/feWx5GUAg/V21HERIUFhVXbUcREhQWFUs5AxFbUAsXBH9KQUBbUBgOfEUP0LSlCVg5Aw84FBYVV21HERIUFhVXbUcREghCUVckAwwQRwQYBz8IVx9NBBdJr+eiDhtCUUlHRxESFBYVV21HERIUFhVXbVtFVhRfUUpvFAMfRERaEWAeAhAK1LXkcUhFVgo8FVdtRxESFBYVV21HERIIGUEFc20REhQWFVdtRxESFBYVV3ETQww+FhVXbUcREhQWFVdtRxESFApBE3MgZ3MUHmZFbYW5oBRlBF5xSEVWCjwVV21HERIUFhVXbUcREhQWCQMpR1hWCRRSASxKU1NHU1keIwITDNa2pktiE1UMPhYVV21HERIUFhVXbUcREhQKQRNtDlUPFlFDFmAeABAK1LXkcUhFVgo8FVdtRxESFBYVV21HERIUFgkDKUdYVgkUUgEsSkgAFgjX995bHkZQCD9XbUcREhQWFVdtRxESFBYVSzkDEVtQCxcQOwYcSwcUC5XN9A0dQFILfW1HERIUFhVXbUcREhQWCVg5FQ84FBYVV21HERIUFhVXbUcNRkYIP1dtRxESFBYVV21HERIUFhVLOQMPYkZZXxIuExFRW0VBV2WlklkdChoDKVk7EhQWFVdtRxESFBYVV21HEQ5AUhUUIgtCQlVYCFV5RRFBQE9ZEnBFRVdMQhgWIQ5WXA4WRx4qD0UJFgg/V21HERIUFhVXbUcREhQWFVdtW1hcRENBVzkeQVcJFFsCIAVUQBYWXBNwRUFAW1xQFDlKUl1HQhgeIxdERhYWQxYhElQPFgYXfW1HERIUFhVXbUcREhQWFVdtRxESR0JMGyhaE0VdUkEfd0cJAkRODlc5AklGGVdZHioJCxJGX1IfOVwRUFtEURI/XREDRE4VBCILWFYUQFQFZUocUFtEURI/TgoSVllHEygVHEBVUlwCPl0RBERODlc9BlVWXVhSTW1TQUoUDkUPdkdXXVpCD1ckCVlXRl9BTG9ZOxIUFhVXbUcREhQWFVdtRxEOG0JRSUdHERIUFhVXbUcREhQWFUtiE0MMPhYVV21HERIUFhVXbUcRDkBEFQQ5Hl1XCRRXFi4MVkBbQ1sTd0cSVwJTARMrXBFUW1hBWj4OS1cOFgQFKAoKEAo8FVdtRxESFBYVV21HERIUFgkDKVllXUBXWVcKMXAOG0JRSUdHERIUFhVXbUcREhQWFVdtW0VWFFVaGz4XUFwJFAFVbQ5VDxZCWgMsCxxVQlcXVz4TSF5RCxcDKB9FH1VaXBAjXRFAXVFdA3ZHV11aQhgAKA5WWkAMFUB9VwoSV1lZGD9dEURVRB1aYAZSUVFYQV52RQ/QtKUJWDkDDzgUFhVXbUcREhQWFVdtRw0dQEQLfW1HERIUFhVXbUcREggZQRUiA0gMPhYVV21HERIUFhVLYhNQUFhTC31tRxESFBYVV3FIQldXQlwYI1k7EhQWFVdtWx5TR19REnNtERIUFglYKQ5HDD4WFUtiClBbWgg/fW1HDRMZGxU1LBRUXl1YUFceE1BAQENFVx0IQUdEFhhac20REghSXAFtDlUPFlRUBCgLWFxRe1oTLAsTEldaVAQ+WhNfW1JUG2AIR1dGWlQOb1k7EhQWFUspDkcSV1pUBD5aE19bUlQbYAReXEBTWwNvWTsSFBYVV21bVVtCFlYbLBRCDxZbWhMsCxxaUVdREj9FDzgUFhVXbUcREgheB0kECVhGXVdZHjcCEXBVRVAbJAlUEnJfUgI/AkIOG14HSUdHERIUFhVXbVtBDGRaUBY+AhFXWkJQBW0TWVcUVFQEKAtYXFEWQxYhElRBFFBaBW00UldaV0ceIkcAEhIWB1ltM1lXR1MVFCwJEVBRFlQTJxJCRlFSFRssE1RAFFBHGCBHRVpRFkYCIApQQE0WWBI5FVhRRzwVV21HERIUFhVXPQZfV1gYCVg9WTsSFBYVV21bHlZdQAt9bUcREhQWCRMkERFRWFdGBHBFXF1QV1laLwhVSxYIP1dtRxESFBYVSykORxJXWlQEPloTX1tSVBtgAVhXWFIXSUdHERIUFhVXbUcRDlhXVxIhR1ddRgsXGiIDUF4ZRFABKAlEVxYIdxY+Al1bWlMVIzgVX11CU0dXYkdjV0JTWwIoRxnwl10cS2ILUFBRWgt9bUcREhQWFVdtRw1bWkZAA20TSEJRCxcZOApTV0YUFR4pWhNfW1JUG2AVVERRWEASb0dHU1hDUEpvUwQCFhZYHiNaEwIWCD9XbUcREhQWFUtiA1hECjwVV21HERIUFgkTJBERUVhXRgRwRVxdUFdZWisOVF5QFAt9bUcREhQWFVdtRw1eVVRQG20BXkAJFFgYKQZdH0REWhEkExMMdldGEiEOX1cUeFADbTdDXVJfQVcPAlddRlMVIywfERr2lV5ecUhdU1ZTWUlHRxESFBYVV21HEQ5dWEUCOUdFS0RTCFUjElxQUUQXVyQDDBBZWVEWIUpBQFtQXANvR0dTWENQSm9TBBAUW1wZcEUBEAo8FVdtRxESFBYJWCkORww+FhVXbUcREhQKUR47R1JeVUVGSm8KXlZVWhgRJAJdVhYIP1dtRxESFBYVV21bXVNWU1lXKwhDDxZbWhMsCxxXWUYYFCISX0YWCHcWPgJdW1pTFTIgF11dTVNQVw4IRFxAChobLAVUXgo8FVdtRxESFBYVV3EOX0JBQhUDNBdUDxZYQBovAkMQFF9RSm8KXlZVWhgSIBccUVtDWwNvR0dTWENQSm9SARAUW1wZcEUAEAo8FVdtRxESFBYJWCkORww+FhVXbUcREhQKUR47R1JeVUVGSm8KXlZVWhgRJAJdVhYIP1dtRxESFBYVV21bXVNWU1lXKwhDDxZbWhMsCxxXWUYYFCIURRAKYloDLAsRQVVaVAU0R1JdR0IVX4/EWhsIGVkWLwJdDD4WFVdtRxESFBYVSyQJQUdAFkEOPQIMEFpDWBUoFRMSXVIIVSAIVVNYG1AaPUpSXUdCF1c7Bl1HUQsXRnhXARAUW1wZcEUBEAo8FVdtRxESFBYJWCkORww+FhVXbUcRDhtSXAFzbRESFBYVV3EDWEQUVVkWPhQMEFlZURYhSlddW0JQBW9ZOxIUFhVXbUcRDlZDQQMiCRFRWFdGBHBFU0ZaFlcDI0pCV1dZWxMsFUgQFF9RSm8KXlZVWhgEJg5BH1ZCW1VzMkJXFHJQESwSXUZHChoVOBNFXVoIP1dtRxESFBYVSy8SRUZbWBUUIQZCQQkUVwMjR1NGWhtFBSQKUEBNFBUeKVoTX1tSVBtgBkFCWE8YFTkJEwx1RkUbNEcXEmdCVAU5Wx5QQUJBGCNZOxIUFhVXbVseVl1AC31tRxESCBlRHjtZOxIUChoTJBEP";

// Authentication and Decryption Logic
function xorDecrypt(base64Text, key) {
  try {
    const binaryString = atob(base64Text);
    const bytes = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
      bytes[i] = binaryString.charCodeAt(i);
    }
    
    const decryptedBytes = new Uint8Array(bytes.length);
    for (let i = 0; i < bytes.length; i++) {
      decryptedBytes[i] = bytes[i] ^ key.charCodeAt(i % key.length);
    }
    
    return new TextDecoder().decode(decryptedBytes);
  } catch (e) {
    console.error("Decryption failed:", e);
    return null;
  }
}

async function sha256(message) {
  const msgBuffer = new TextEncoder().encode(message);
  const hashBuffer = await crypto.subtle.digest('SHA-256', msgBuffer);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

async function checkAuth() {
  const isAuth = sessionStorage.getItem('gva_auth') === 'true';
  const key = sessionStorage.getItem('gva_key');
  const appRoot = document.getElementById('app-root');
  const loginOverlay = document.getElementById('loginOverlay');
  
  if (isAuth && key) {
    const decryptedHtml = xorDecrypt(ENCRYPTED_DASHBOARD, key);
    
    if (decryptedHtml && decryptedHtml.includes('id="app-main"')) {
      loginOverlay.classList.add('hidden');
      appRoot.innerHTML = decryptedHtml;
      
      const appMain = document.getElementById('app-main');
      if (appMain) {
        appMain.style.display = 'block';
      }
      
      initializeDashboard();
      return;
    }
  }
  
  // Reset session storage if decryption failed or not authenticated
  sessionStorage.removeItem('gva_auth');
  sessionStorage.removeItem('gva_key');
  appRoot.innerHTML = '';
  loginOverlay.classList.remove('hidden');
  document.getElementById('login-username').focus();
}

async function handleLogin(event) {
  event.preventDefault();
  const userEl = document.getElementById('login-username');
  const passEl = document.getElementById('login-password');
  const errorEl = document.getElementById('loginError');
  const errorMsgEl = document.getElementById('loginErrorMsg');
  
  const username = userEl.value.trim();
  const password = passEl.value;
  
  // Clear previous error state
  userEl.style.borderColor = '';
  passEl.style.borderColor = '';
  errorEl.style.display = 'none';

  const userHash = await sha256(username);
  const passHash = await sha256(password);

  // Correct credentials: username WMGSME, password wMg12465
  const CORRECT_USER_HASH = 'df8f1bbf8d66df1e5ae42d79b4cbdcc249f4d2b40974605e93b93ba025cc949b';
  const CORRECT_PASS_HASH = 'ea4629264eb996a075c5bf8bdb9be1a095b86e4dff3339656ddac6f2a779a0b2';

  if (userHash === CORRECT_USER_HASH && passHash === CORRECT_PASS_HASH) {
    sessionStorage.setItem('gva_auth', 'true');
    sessionStorage.setItem('gva_key', password); // Used locally as key
    await checkAuth();
  } else {
    // Show error and apply shake animation
    errorMsgEl.textContent = 'Invalid username or password. Please try again.';
    errorEl.style.display = 'flex';
    userEl.style.borderColor = '#d9534f';
    passEl.style.borderColor = '#d9534f';
    
    // Re-trigger shake animation
    errorEl.style.animation = 'none';
    errorEl.offsetHeight; // trigger reflow
    errorEl.style.animation = null;
  }
}

function handleLogout() {
  sessionStorage.removeItem('gva_auth');
  sessionStorage.removeItem('gva_key');
  
  // Reset input fields in login form
  document.getElementById('login-username').value = '';
  document.getElementById('login-password').value = '';
  document.getElementById('loginError').style.display = 'none';
  document.getElementById('login-username').style.borderColor = '';
  document.getElementById('login-password').style.borderColor = '';
  
  checkAuth();
}

// Global variables for dashboard
let baseYear;
let yr1, yr2, yr3;
let labels;
let scenario1, scenario2;
let refreshProfit1, refreshProfit2;

// Dynamic Base Year Shifting Logic
function getBaseYear() {
  const today = new Date();
  const year = today.getFullYear();
  const month = today.getMonth(); // 0-indexed (April = 3)
  return (month >= 3) ? year : (year - 1);
}

baseYear = getBaseYear();
yr1 = baseYear + 1;
yr2 = baseYear + 2;
yr3 = baseYear + 3;
labels = ['Baseline (' + baseYear + ')', String(yr1), String(yr2), String(yr3)];

function initializeDynamicHeaders() {
  document.querySelectorAll('.col-yr-1').forEach(el => el.textContent = yr1);
  document.querySelectorAll('.col-yr-2').forEach(el => el.textContent = yr2);
  document.querySelectorAll('.col-yr-3').forEach(el => el.textContent = yr3);

  document.querySelectorAll('.lbl-yr-1').forEach(el => el.textContent = yr1);
  document.querySelectorAll('.lbl-yr-2').forEach(el => el.textContent = yr2);
  document.querySelectorAll('.lbl-yr-3').forEach(el => el.textContent = yr3);
}

function updateBaseYear(newBaseYear) {
  baseYear = parseInt(newBaseYear);
  yr1 = baseYear + 1;
  yr2 = baseYear + 2;
  yr3 = baseYear + 3;
  labels = ['Baseline (' + baseYear + ')', String(yr1), String(yr2), String(yr3)];

  initializeDynamicHeaders();

  if (scenario1) scenario1.updateLabels(labels);
  if (scenario2) scenario2.updateLabels(labels);

  const p1Labels = document.querySelectorAll('#profitGrid1 .profit-label');
  const p2Labels = document.querySelectorAll('#profitGrid2 .profit-label');
  [p1Labels, p2Labels].forEach(labelsGroup => {
    if (labelsGroup.length >= 4) {
      labelsGroup[0].textContent = 'Baseline net profit as % of revenue';
      labelsGroup[1].textContent = `${yr1} net profit as % of revenue`;
      labelsGroup[2].textContent = `${yr2} net profit as % of revenue`;
      labelsGroup[3].textContent = `${yr3} net profit as % of revenue`;
    }
  });
}

// Global stores (values in £k)
const netProfitK = {
  s1: [0, 0, 0, 0],
  s2: [0, 0, 0, 0]
};
const employeeCostK = {
  s1: [0, 0, 0, 0],
  s2: [0, 0, 0, 0]
};

function formatCurrencyK(k) {
  const full = Math.round(k * 1000);
  return (full < 0 ? '-' : '') + '£' + Math.abs(full).toLocaleString();
}

function updateSummaryTable() {
  const tableMap = {
    s1Emp: ['s1-emp-baseline', 's1-emp-y1', 's1-emp-y2', 's1-emp-y3'],
    s1Prof: ['s1-prof-baseline', 's1-prof-y1', 's1-prof-y2', 's1-prof-y3'],
    s2Emp: ['s2-emp-baseline', 's2-emp-y1', 's2-emp-y2', 's2-emp-y3'],
    s2Prof: ['s2-prof-baseline', 's2-prof-y1', 's2-prof-y2', 's2-prof-y3'],
    gva: ['gva-baseline', 'gva-y1', 'gva-y2', 'gva-y3']
  };

  let totalGvaY1toY3 = 0;

  for (let i = 0; i < 4; i++) {
    document.getElementById(tableMap.s1Emp[i]).textContent =
      employeeCostK.s1[i] ? formatCurrencyK(employeeCostK.s1[i]) : '£0';
    document.getElementById(tableMap.s1Prof[i]).textContent =
      netProfitK.s1[i] ? formatCurrencyK(netProfitK.s1[i]) : '£0';

    document.getElementById(tableMap.s2Emp[i]).textContent =
      employeeCostK.s2[i] ? formatCurrencyK(employeeCostK.s2[i]) : '£0';
    document.getElementById(tableMap.s2Prof[i]).textContent =
      netProfitK.s2[i] ? formatCurrencyK(netProfitK.s2[i]) : '£0';

    const totalS1 = (employeeCostK.s1[i] || 0) + (netProfitK.s1[i] || 0);
    const totalS2 = (employeeCostK.s2[i] || 0) + (netProfitK.s2[i] || 0);
    const gvaK = totalS2 - totalS1;
    document.getElementById(tableMap.gva[i]).textContent = formatCurrencyK(gvaK);

    if (i >= 1 && i <= 3) {
      totalGvaY1toY3 += gvaK;
    }
  }

  const projectCostInput = document.getElementById('project-cost-input');
  const projectCost = projectCostInput ? Number(projectCostInput.value) : 0;
  const totalGva = totalGvaY1toY3 + projectCost;

  const totalGvaEl = document.getElementById('total-gva');
  if (totalGvaEl) {
    totalGvaEl.textContent = formatCurrencyK(totalGva);
  }
}

function createScenarioChart({ svgId, summaryId, title, series, onUpdate }) {
  const svg = document.getElementById(svgId);
  const summary = document.getElementById(summaryId);
  const NS = 'http://www.w3.org/2000/svg';
  const plot = { left: 72, top: 26, width: 500, height: 270, right: 572, bottom: 296 };
  let maxRevenue = 10000;
  let minRevenue = 200;
  const data = series.map(item => ({ ...item }));
  const xStep = plot.width / (data.length - 1);
  const pointElements = [];
  const tagElements = [];

  svg.innerHTML = `
    <defs>
      <clipPath id="clip-${svgId}">
        <rect x="${plot.left}" y="${plot.top}" width="${plot.width}" height="${plot.height}" rx="12" ry="12"></rect>
      </clipPath>
    </defs>
    <g class="grid"></g>
    <g class="axes"></g>
    <path class="area" clip-path="url(#clip-${svgId})"></path>
    <path class="trend" clip-path="url(#clip-${svgId})"></path>
    <g class="points"></g>
    <g class="x-labels"></g>
    <g class="y-labels"></g>
    <text x="20" y="164" transform="rotate(-90 20 164)" class="label">Revenue</text>
    <text x="296" y="364" class="label">Time</text>
  `;

  const gridGroup = svg.querySelector('.grid');
  const axesGroup = svg.querySelector('.axes');
  const area = svg.querySelector('.area');
  const line = svg.querySelector('.trend');
  const pointsGroup = svg.querySelector('.points');
  const xLabelsGroup = svg.querySelector('.x-labels');
  const yLabelsGroup = svg.querySelector('.y-labels');

  function make(tag, attrs = {}, parent) {
    const el = document.createElementNS(NS, tag);
    Object.entries(attrs).forEach(([k, v]) => el.setAttribute(k, v));
    if (parent) parent.appendChild(el);
    return el;
  }

  summary.innerHTML = data.map((d, i) => `
    <div class="metric">
      <small>${d.label}</small>
      ${i === 0 ? `
        <div style="display: flex; align-items: center; gap: 2px;">
          <span style="font-size: 0.9rem; font-weight: 700;">£</span>
          <input type="number" id="revenue-input-${svgId}-${i}" value="${Math.round(d.value)}" style="width: 50px; font: inherit; font-size: 0.9rem; font-weight: 700; padding: 2px; border: 1px solid var(--border); border-radius: 6px; text-align: right; color: var(--accent);">
          <span style="font-size: 0.9rem; font-weight: 700;">k</span>
        </div>
      ` : `
        <div style="display: flex; flex-direction: column; gap: 2px;">
          <strong id="revenue-text-${svgId}-${i}"></strong>
          <div id="yoy-text-${svgId}-${i}" style="font-size: 0.75rem; color: var(--accent); font-weight: 600;"></div>
        </div>
      `}
    </div>
  `).join('');

  const revInputs = data.map((d, i) => i === 0 ? document.getElementById(`revenue-input-${svgId}-${i}`) : document.getElementById(`revenue-text-${svgId}-${i}`));

  if (revInputs[0]) {
    revInputs[0].addEventListener('input', (e) => {
      const val = Number(e.target.value);
      data.forEach(d => d.value = val);
      update();
    });
  }

  function xForIndex(i) { return plot.left + i * xStep; }
  function yForValue(value) {
    const ratio = (value - minRevenue) / (maxRevenue - minRevenue);
    return plot.bottom - ratio * plot.height;
  }
  function valueForY(y) {
    const clampedY = Math.max(plot.top, Math.min(plot.bottom, y));
    const ratio = (plot.bottom - clampedY) / plot.height;
    return Math.round((minRevenue + ratio * (maxRevenue - minRevenue)) * 10) / 10;
  }
  function pointerY(event) {
    const rect = svg.getBoundingClientRect();
    const scaleY = svg.viewBox.baseVal.height / rect.height;
    return (event.clientY - rect.top) * scaleY;
  }
  function renderYAxis() {
    yLabelsGroup.innerHTML = '';
    gridGroup.innerHTML = '';
    const step = (maxRevenue - minRevenue) / 10;
    for (let i = 0; i <= 10; i++) {
      const tick = minRevenue + step * i;
      const y = yForValue(tick);
      make('line', { x1: plot.left, y1: y, x2: plot.right, y2: y, class: 'grid-line' }, gridGroup);
      const label = make('text', { x: plot.left - 12, y: y + 4, 'text-anchor': 'end', class: 'label' }, yLabelsGroup);
      label.textContent = '£' + Math.round(tick) + 'k';
    }
  }

  make('line', { x1: plot.left, y1: plot.top, x2: plot.left, y2: plot.bottom, class: 'axis' }, axesGroup);
  make('line', { x1: plot.left, y1: plot.bottom, x2: plot.right, y2: plot.bottom, class: 'axis' }, axesGroup);

  data.forEach((d, i) => {
    const x = xForIndex(i);
    make('line', { x1: x, y1: plot.bottom, x2: x, y2: plot.bottom + 6, class: 'axis' }, axesGroup);
    const txt = make('text', { x, y: plot.bottom + 24, 'text-anchor': 'middle', class: 'label' }, xLabelsGroup);
    txt.textContent = d.label;
    const g = make('g', {}, pointsGroup);
    const tag = make('g', { class: 'value-tag' }, g);
    const rect = make('rect', { width: 64, height: 26, x: x - 32, y: 0 }, tag);
    const text = make('text', { x, y: 17, 'text-anchor': 'middle' }, tag);
    const point = make('circle', {
      cx: x,
      cy: yForValue(d.value),
      r: 8.5,
      class: 'point',
      tabindex: '0',
      'aria-label': `Drag ${title} ${d.label} revenue`
    }, g);
    point.dataset.index = i;
    pointElements.push(point);
    tagElements.push({ group: tag, rect, text });
  });

  function formatRevenue(v) { return '£' + Math.round(v * 1000).toLocaleString(); }

  function update() {
    renderYAxis();
    const coords = data.map((d, i) => [xForIndex(i), yForValue(d.value)]);
    const linePath = coords.map((p, i) => `${i === 0 ? 'M' : 'L'} ${p[0]} ${p[1]}`).join(' ');
    line.setAttribute('d', linePath);
    area.setAttribute('d', `${linePath} L ${coords[coords.length - 1][0]} ${plot.bottom} L ${coords[0][0]} ${plot.bottom} Z`);

    data.forEach((d, i) => {
      const x = xForIndex(i);
      const y = yForValue(d.value);
      pointElements[i].setAttribute('cx', x);
      pointElements[i].setAttribute('cy', y);
      const tag = tagElements[i];
      tag.group.setAttribute('transform', `translate(0, ${y - 38})`);
      tag.text.textContent = formatRevenue(d.value);
      const width = Math.max(64, tag.text.getComputedTextLength() + 22);
      tag.rect.setAttribute('width', width);
      tag.rect.setAttribute('x', x - width / 2);
      tag.text.setAttribute('x', x);
    });

    data.forEach((d, i) => {
      if (i === 0) {
        if (document.activeElement !== revInputs[0]) {
          revInputs[0].value = Math.round(d.value);
        }
      } else {
        revInputs[i].textContent = formatRevenue(d.value);
        const prevValue = data[i - 1].value;
        const growth = prevValue ? ((d.value - prevValue) / prevValue) * 100 : 0;
        const sign = growth > 0 ? '+' : '';
        const yoyEl = document.getElementById(`yoy-text-${svgId}-${i}`);
        if (yoyEl) {
          yoyEl.textContent = `${sign}${growth.toFixed(1)}% YoY`;
          yoyEl.style.color = growth < 0 ? '#d9534f' : 'var(--accent)';
        }
      }
    });

    if (onUpdate) onUpdate(data);
  }

  let activeIndex = null;
  function startDrag(event) {
    const target = event.target.closest('.point');
    if (!target) return;
    activeIndex = Number(target.dataset.index);
    target.classList.add('active');
  }
  function moveDrag(event) {
    if (activeIndex === null) return;
    const val = valueForY(pointerY(event));
    if (activeIndex === 0) {
      data.forEach(d => d.value = val);
    } else {
      data[activeIndex].value = val;
    }
    update();
  }
  function endDrag() {
    if (activeIndex === null) return;
    pointElements[activeIndex].classList.remove('active');
    activeIndex = null;
  }
  svg.addEventListener('pointerdown', (event) => {
    startDrag(event);
    if (activeIndex !== null) svg.setPointerCapture(event.pointerId);
  });
  svg.addEventListener('pointermove', moveDrag);
  svg.addEventListener('pointerup', (event) => {
    endDrag();
    if (svg.hasPointerCapture(event.pointerId)) svg.releasePointerCapture(event.pointerId);
  });
  svg.addEventListener('pointercancel', endDrag);
  svg.addEventListener('pointerleave', endDrag);
  update();

  return {
    getData: () => data.map(item => ({ ...item })),
    setDataValue: (idx, val) => {
      if (idx === 0) {
        data.forEach(d => d.value = val);
      } else {
        data[idx].value = val;
      }
      update();
    },
    setYRange: (min, max) => {
      minRevenue = min;
      maxRevenue = max;
      update();
    },
    refresh: update,
    setValues: (newValues) => {
      newValues.forEach((val, i) => {
        data[i].value = val;
      });
      update();
    },
    updateLabels: (newLabels) => {
      data.forEach((d, i) => {
        d.label = newLabels[i];
      });
      const txtElements = svg.querySelectorAll('.x-labels text');
      txtElements.forEach((txt, i) => {
        if (newLabels[i]) txt.textContent = newLabels[i];
      });
      const legendItems = summary.querySelectorAll('.metric small');
      legendItems.forEach((small, i) => {
        if (newLabels[i]) small.textContent = newLabels[i];
      });
      update();
    }
  };
}

function applyYoYGrowth(scenarioKey, percent) {
  const scenario = scenarioKey === 's1' ? scenario1 : scenario2;
  const currentData = scenario.getData();
  const baseline = currentData[0].value;
  const newValues = [baseline];

  for (let i = 1; i < currentData.length; i++) {
    const prevValue = newValues[i - 1];
    newValues.push(prevValue * (1 + percent / 100));
  }

  scenario.setValues(newValues);
}

function applyProfitPreset(scenarioKey, delta) {
  const refreshFn = scenarioKey === 's1' ? refreshProfit1 : refreshProfit2;
  const baselinePct = refreshFn.rawMargins[0];

  for (let i = 1; i <= 3; i++) {
    const newValue = baselinePct + (delta * i);
    refreshFn.rawMargins[i] = newValue;
  }
  refreshFn();
}

function createProfitControls({ containerId, scenarioKey, scenarioName, defaultPercents, getScenarioData }) {
  const container = document.getElementById(containerId);
  const years = ['Baseline', String(yr1), String(yr2), String(yr3)];
  const rawMargins = [...defaultPercents];

  container.innerHTML = years.map((year, i) => `
    <div class="profit-row">
      <div class="profit-head">
        <div class="profit-label">${year} net profit as % of revenue</div>
        <div style="display: flex; align-items: center; gap: 2px;">
          <input type="number" class="profit-percent-input" id="${containerId}-percent-input-${i}" value="${defaultPercents[i]}" step="0.01" style="width: 65px; text-align: right; border: 1px solid var(--border); border-radius: 6px; padding: 4px; font-size: 0.95rem; font-weight: 700; color: var(--accent); font-family: inherit;" ${i === 0 ? 'readonly style="background: #fafaf9; border-color: transparent;"' : ''}>
          <span class="profit-percent">%</span>
        </div>
      </div>
      ${i === 0 ? '' : `<input class="profit-slider" id="${containerId}-slider-${i}" type="range" min="-100" max="80" step="1" value="${defaultPercents[i]}" aria-label="${scenarioName} ${year} net profit percentage">`}
      <div class="profit-number">
        <span style="margin-right: 4px;">Net profit value:</span>
        ${i === 0 ? `
          <div style="display: inline-flex; align-items: center; gap: 2px; vertical-align: middle;">
            <span style="color: var(--text);">£</span>
            <input type="number" id="${containerId}-amount-input-${i}" style="width: 70px; text-align: right; border: 1px solid var(--border); border-radius: 6px; padding: 2px 4px; font-size: 0.92rem; font-family: inherit;">
            <span style="color: var(--text);">k</span>
          </div>
        ` : `<span id="${containerId}-value-${i}" style="color: var(--text);"></span>`}
      </div>
    </div>
  `).join('');

  function refresh(sourceId) {
    const data = getScenarioData();
    years.forEach((year, i) => {
      const slider = document.getElementById(`${containerId}-slider-${i}`);
      const percentInput = document.getElementById(`${containerId}-percent-input-${i}`);
      const valueSpan = document.getElementById(`${containerId}-value-${i}`);
      const amountInput = document.getElementById(`${containerId}-amount-input-${i}`);
      const revenue = data[i].value;

      let pct;
      let profitK;

      if (amountInput && sourceId === amountInput.id) {
        profitK = Number(amountInput.value);
        pct = revenue ? (profitK / revenue) * 100 : 0;
        pct = Math.round(pct * 100) / 100;
        rawMargins[i] = pct;
      } else if (slider && sourceId === slider.id) {
        pct = Number(slider.value);
        rawMargins[i] = pct;
      } else if (percentInput && sourceId === percentInput.id) {
        pct = Number(percentInput.value);
        rawMargins[i] = pct;
      } else {
        pct = rawMargins[i];
      }

      profitK = revenue * (pct / 100);

      let addedSalaryCost = 0;
      if (i > 0) {
        addedSalaryCost = (employeeCostK[scenarioKey][i] || 0) - (employeeCostK[scenarioKey][0] || 0);
        profitK -= addedSalaryCost;
      }

      const adjustedPct = revenue ? (profitK / revenue) * 100 : 0;
      const roundedAdjustedPct = Math.round(adjustedPct * 100) / 100;

      if (percentInput && sourceId !== percentInput.id) {
        percentInput.value = roundedAdjustedPct;
      }
      if (slider && sourceId !== slider.id) {
        slider.value = Math.round(adjustedPct);
      }
      if (amountInput && sourceId !== amountInput.id) {
        amountInput.value = Number(profitK.toFixed(2));
      }

      if (valueSpan) {
        if (i > 0 && addedSalaryCost > 0) {
          valueSpan.innerHTML = `${formatCurrencyK(profitK)} <span style="font-size: 0.8rem; color: #d9534f; font-weight: 600; margin-left: 6px;">(-${formatCurrencyK(addedSalaryCost)} payroll adjustment)</span>`;
        } else {
          valueSpan.textContent = formatCurrencyK(profitK);
        }
      }
      netProfitK[scenarioKey][i] = profitK;
    });
    updateSummaryTable();
  }

  refresh.rawMargins = rawMargins;

  years.forEach((_, i) => {
    const slider = document.getElementById(`${containerId}-slider-${i}`);
    if (slider) {
      slider.addEventListener('input', (e) => refresh(e.target.id));
    }
    const pctInput = document.getElementById(`${containerId}-percent-input-${i}`);
    if (pctInput) {
      pctInput.addEventListener('input', (e) => refresh(e.target.id));
    }
    const amountInput = document.getElementById(`${containerId}-amount-input-${i}`);
    if (amountInput) {
      amountInput.addEventListener('input', (e) => refresh(e.target.id));
    }
  });

  refresh();
  return refresh;
}

function createEmployeeLogic(prefix, scenarioKey) {
  const baselineInput = document.getElementById(`${prefix}-baseline`);
  const costInput = document.getElementById(`${prefix}-cost`);
  const y1Input = document.getElementById(`${prefix}-y1`);
  const y2Input = document.getElementById(`${prefix}-y2`);
  const y3Input = document.getElementById(`${prefix}-y3`);
  const metric = document.getElementById(`${prefix}-metric`);

  function update() {
    const costPerEmployee = Math.max(0, Number(costInput.value / baselineInput.value) || 0);
    const counts = [
      Math.max(0, Number(baselineInput.value) || 0),
      Math.max(0, Number(y1Input.value) || 0),
      Math.max(0, Number(y2Input.value) || 0),
      Math.max(0, Number(y3Input.value) || 0)
    ];
    const annualCosts = counts.map(c => c * costPerEmployee);

    metric.innerHTML = `Average cost per employee: <strong>${formatCurrencyK(costPerEmployee)}</strong><br>` +
      `Annual employee cost: Base ${formatCurrencyK(annualCosts[0])}, ${yr1} ${formatCurrencyK(annualCosts[1])}, ${yr2} ${formatCurrencyK(annualCosts[2])}, ${yr3} ${formatCurrencyK(annualCosts[3])}`;

    employeeCostK[scenarioKey] = annualCosts;
    const refreshProfit = scenarioKey === 's1' ? refreshProfit1 : refreshProfit2;
    if (typeof refreshProfit === 'function') {
      refreshProfit();
    } else {
      updateSummaryTable();
    }
  }

  [baselineInput, costInput, y1Input, y2Input, y3Input].forEach(input => {
    input.addEventListener('input', update);
  });
  update();
  return update;
}

// Scenario 2 Custom Employment Logic
const BAND_SALARIES = [15, 20.4, 30, 40, 50, 65]; // £k

function updateEmployee2() {
  const baselineInput = document.getElementById('emp2-baseline');
  const costInput = document.getElementById('emp2-cost');
  const metric = document.getElementById('emp2-metric');

  const baselineCount = Math.max(0, Number(baselineInput.value) || 0);
  const baselineCost = Math.max(0, Number(costInput.value) || 0);
  const baselineAvgSalary = baselineCount ? (baselineCost / baselineCount) : 0;

  const newJobsByYear = [0, 0, 0]; // Y1, Y2, Y3 indices
  const costAddedByYear = [0, 0, 0];
  const bandTotals = [0, 0, 0, 0, 0, 0];

  const bandInputs = document.querySelectorAll('.band-input');
  bandInputs.forEach(input => {
    const bandIdx = parseInt(input.dataset.band);
    const yearIdx = parseInt(input.dataset.yearIdx);
    const val = Math.max(0, parseInt(input.value) || 0);

    newJobsByYear[yearIdx - 1] += val;
    costAddedByYear[yearIdx - 1] += val * BAND_SALARIES[bandIdx];
    bandTotals[bandIdx] += val;
  });

  for (let i = 0; i < 6; i++) {
    document.getElementById(`band-total-${i}`).textContent = bandTotals[i];
  }

  let grandTotalNewJobs = 0;
  let cumulativeNewJobs = 0;
  for (let idx = 1; idx <= 3; idx++) {
    const colTotal = newJobsByYear[idx - 1];
    cumulativeNewJobs += colTotal;
    document.getElementById(`band-col-total-y${idx}`).textContent = colTotal;
    document.getElementById(`forecast-new-y${idx}`).textContent = colTotal;
    grandTotalNewJobs += colTotal;

    const c1Input = document.getElementById(`emp1-y${idx}`);
    const c2Input = document.getElementById(`emp2-y${idx}`);
    if (c1Input && c2Input) {
      const c1 = Math.max(0, parseInt(c1Input.value) || 0);
      c2Input.value = c1 + cumulativeNewJobs;
    }
  }
  document.getElementById('band-grand-total').textContent = grandTotalNewJobs;
  document.getElementById('forecast-new-total').textContent = grandTotalNewJobs;

  let grandTotalUpskilled = 0;
  for (let idx = 1; idx <= 3; idx++) {
    const val = Math.max(0, parseInt(document.getElementById(`upskilled-y${idx}`).value) || 0);
    grandTotalUpskilled += val;
  }
  document.getElementById('upskilled-total').textContent = grandTotalUpskilled;

  const counts = [baselineCount];
  const costs = [baselineCost];

  counts.push(counts[0] + newJobsByYear[0]);
  costs.push(costs[0] + costAddedByYear[0]);

  counts.push(counts[1] + newJobsByYear[1]);
  costs.push(costs[1] + costAddedByYear[1]);

  counts.push(counts[2] + newJobsByYear[2]);
  costs.push(costs[2] + costAddedByYear[2]);

  metric.innerHTML = `Baseline Avg Salary: <strong>${formatCurrencyK(baselineAvgSalary)}</strong><br>` +
    `Headcount: Base <strong>${counts[0]}</strong>, ${yr1} <strong>${counts[1]}</strong>, ${yr2} <strong>${counts[2]}</strong>, ${yr3} <strong>${counts[3]}</strong><br>` +
    `Payroll Cost: Base <strong>${formatCurrencyK(costs[0])}</strong>, ${yr1} <strong>${formatCurrencyK(costs[1])}</strong>, ${yr2} <strong>${formatCurrencyK(costs[2])}</strong>, ${yr3} <strong>${formatCurrencyK(costs[3])}</strong>`;

  employeeCostK.s2 = costs;
  if (typeof refreshProfit2 === 'function') {
    refreshProfit2();
  } else {
    updateSummaryTable();
  }
}

// Set initial baseline callbacks
function syncChartScales(baseline) {
  if (!scenario1 || !scenario2) return;
  const min = Math.max(0, baseline * 0.6);
  const max = baseline * 1.8;
  scenario1.setYRange(min, max);
  scenario2.setYRange(min, max);
}

function syncProfitBaseline() {
  const s1Pct = refreshProfit1.rawMargins[0];
  if (refreshProfit2.rawMargins[0] !== s1Pct) {
    refreshProfit2.rawMargins[0] = s1Pct;
    refreshProfit2();
  }
}

function syncEmpBaseline(e, targetId) {
  const target = document.getElementById(targetId);
  if (target.value !== e.target.value) {
    target.value = e.target.value;
    target.dispatchEvent(new Event('input'));
  }
}

function syncCountToBands(yearIdx) {
  const c1Input = document.getElementById(`emp1-y${yearIdx}`);
  const c2Input = document.getElementById(`emp2-y${yearIdx}`);
  if (!c1Input || !c2Input) return;

  const c1 = Math.max(0, parseInt(c1Input.value) || 0);
  const c2 = Math.max(0, parseInt(c2Input.value) || 0);
  const targetDiff = Math.max(0, c2 - c1);

  let prevNewJobs = 0;
  for (let i = 1; i < yearIdx; i++) {
    const prevInputs = document.querySelectorAll(`.band-input[data-year-idx="${i}"]`);
    prevInputs.forEach(input => {
      prevNewJobs += Math.max(0, parseInt(input.value) || 0);
    });
  }

  const targetNewJobsThisYear = Math.max(0, targetDiff - prevNewJobs);
  const inputs = Array.from(document.querySelectorAll(`.band-input[data-year-idx="${yearIdx}"]`));
  const currentSum = inputs.reduce((sum, input) => sum + (parseInt(input.value) || 0), 0);

  const diff = targetNewJobsThisYear - currentSum;
  if (diff === 0) return;

  if (diff > 0) {
    const band2Input = inputs.find(input => input.dataset.band === "2");
    if (band2Input) {
      band2Input.value = (parseInt(band2Input.value) || 0) + diff;
    }
  } else {
    let toSubtract = Math.abs(diff);
    const band2Input = inputs.find(input => input.dataset.band === "2");
    if (band2Input) {
      const val = parseInt(band2Input.value) || 0;
      const sub = Math.min(val, toSubtract);
      band2Input.value = val - sub;
      toSubtract -= sub;
    }
    if (toSubtract > 0) {
      for (const input of inputs) {
        if (input.dataset.band === "2") continue;
        const val = parseInt(input.value) || 0;
        const sub = Math.min(val, toSubtract);
        input.value = val - sub;
        toSubtract -= sub;
        if (toSubtract === 0) break;
      }
    }
  }
  updateEmployee2();
}

// Standalone Modal Functions
function showBaselineModal() {
  document.getElementById('modal-revenue').value = Math.round(scenario1.getData()[0].value);
  const s1AmtInput = document.getElementById('profitGrid1-amount-input-0');
  document.getElementById('modal-profit').value = s1AmtInput ? Math.round(Number(s1AmtInput.value)) : 45;
  document.getElementById('modal-emp-count').value = document.getElementById('emp1-baseline').value;
  document.getElementById('modal-emp-cost').value = document.getElementById('emp1-cost').value;
  document.getElementById('baselineModal').classList.add('active');
}

function hideBaselineModal() {
  document.getElementById('baselineModal').classList.remove('active');
}

function handleApplyBaseline() {
  const rev = Number(document.getElementById('modal-revenue').value);
  const profitVal = Number(document.getElementById('modal-profit').value);
  const count = Number(document.getElementById('modal-emp-count').value);
  const cost = Number(document.getElementById('modal-emp-cost').value);

  scenario1.setDataValue(0, rev);

  const emp1Base = document.getElementById('emp1-baseline');
  const emp1Cost = document.getElementById('emp1-cost');
  emp1Base.value = count;
  emp1Cost.value = cost;

  document.getElementById('emp1-y1').value = count;
  document.getElementById('emp1-y2').value = count;
  document.getElementById('emp1-y3').value = count;

  emp1Base.dispatchEvent(new Event('input'));
  emp1Cost.dispatchEvent(new Event('input'));

  const bandInputs = document.querySelectorAll('.band-input');
  bandInputs.forEach(input => {
    input.value = 0;
  });
  updateEmployee2();

  const basePct = rev ? Math.round((profitVal / rev) * 100 * 100) / 100 : 10;

  for (let i = 0; i < 4; i++) {
    refreshProfit1.rawMargins[i] = basePct;
  }
  for (let i = 0; i < 4; i++) {
    refreshProfit2.rawMargins[i] = basePct;
  }

  refreshProfit1();
  refreshProfit2();

  hideBaselineModal();
  sessionStorage.setItem('gva_baseline_initialized', 'true');
}

function handleSkipBaseline() {
  hideBaselineModal();
  sessionStorage.setItem('gva_baseline_initialized', 'true');
}

// Standalone CSV Operations
function handleExport() {
  const csv = [];

  function serializeTable(tableId, title) {
    const table = document.getElementById(tableId);
    if (!table) return;
    csv.push(`"${title}"`);
    const rows = table.querySelectorAll('tr');
    for (let i = 0; i < rows.length; i++) {
      const row = [];
      const cols = rows[i].querySelectorAll('td, th');
      for (let j = 0; j < cols.length; j++) {
        const cell = cols[j];
        let cellText = '';
        const numInput = cell.querySelector('input[type="number"]');
        const txtInput = cell.querySelector('input[type="text"]');
        if (numInput) {
          if (tableId === 'summaryTable' && cellText.includes('cost')) {
            cellText = '£' + numInput.value + 'k';
          } else {
            cellText = numInput.value;
          }
        } else if (txtInput) {
          cellText = txtInput.value;
        } else {
          cellText = cell.innerText.replace(/(\r\n|\n|\r)/gm, ' ').trim();
        }
        cellText = '"' + cellText.replace(/"/g, '""') + '"';
        row.push(cellText);
      }
      csv.push(row.join(','));
    }
    csv.push('');
  }

  serializeTable('summaryTable', 'Summary Metrics');

  const s2ForecastTable = document.querySelector('.forecast-table');
  if (s2ForecastTable) {
    csv.push('"Scenario 2 Employment & Skills Forecast"');
    const rows = s2ForecastTable.querySelectorAll('tr');
    for (let i = 0; i < rows.length; i++) {
      const row = [];
      const cols = rows[i].querySelectorAll('td, th');
      for (let j = 0; j < cols.length; j++) {
        const cell = cols[j];
        let cellText = '';
        const numInput = cell.querySelector('input[type="number"]');
        const txtInput = cell.querySelector('input[type="text"]');
        if (numInput) {
          cellText = numInput.value;
        } else if (txtInput) {
          cellText = txtInput.value;
        } else {
          cellText = cell.innerText.replace(/(\r\n|\n|\r)/gm, ' ').trim();
        }
        cellText = '"' + cellText.replace(/"/g, '""') + '"';
        row.push(cellText);
      }
      csv.push(row.join(','));
    }
    csv.push('');
  }

  const s2BandsTable = document.querySelector('.bands-table');
  if (s2BandsTable) {
    csv.push('"Scenario 2 Salary Bands of New Jobs Created"');
    const rows = s2BandsTable.querySelectorAll('tr');
    for (let i = 0; i < rows.length; i++) {
      const row = [];
      const cols = rows[i].querySelectorAll('td, th');
      for (let j = 0; j < cols.length; j++) {
        const cell = cols[j];
        let cellText = '';
        const numInput = cell.querySelector('input[type="number"]');
        if (numInput) {
          cellText = numInput.value;
        } else {
          cellText = cell.innerText.replace(/(\r\n|\n|\r)/gm, ' ').trim();
        }
        cellText = '"' + cellText.replace(/"/g, '""') + '"';
        row.push(cellText);
      }
      csv.push(row.join(','));
    }
    csv.push('');
  }

  csv.push('"Model Inputs"');
  csv.push('"Parameter","Base","Y1","Y2","Y3"');
  csv.push(`"Base Year",${baseYear},,,`);
  
  const s1Data = scenario1.getData();
  csv.push(`"S1 Revenue",${s1Data.map(d => d.value).join(',')}`);
  
  const s2Data = scenario2.getData();
  csv.push(`"S2 Revenue",${s2Data.map(d => d.value).join(',')}`);
  
  const s1Margins = [0, 1, 2, 3].map(i => refreshProfit1.rawMargins[i]);
  csv.push(`"S1 Profit Margin %",${s1Margins.join(',')}`);
  
  const s2Margins = [0, 1, 2, 3].map(i => refreshProfit2.rawMargins[i]);
  csv.push(`"S2 Profit Margin %",${s2Margins.join(',')}`);
  
  const s1Emp = [
    document.getElementById('emp1-baseline').value,
    document.getElementById('emp1-y1').value,
    document.getElementById('emp1-y2').value,
    document.getElementById('emp1-y3').value
  ];
  csv.push(`"S1 Employee Count",${s1Emp.join(',')}`);
  
  const s1EmpCost = document.getElementById('emp1-cost').value;
  csv.push(`"Baseline Employee Cost",${s1EmpCost},,,`);
  
  const projCost = document.getElementById('project-cost-input').value;
  csv.push(`"Project Cost",${projCost},,,`);
  
  const s2Upskilled = [1, 2, 3].map(i => document.getElementById(`upskilled-y${i}`).value);
  csv.push(`"S2 Upskilled Count",${s2Upskilled.join(',')},`);
  
  const s2SkillsNotes = [1, 2, 3].map(i => '"' + document.getElementById(`skills-note-y${i}`).value.replace(/"/g, '""') + '"');
  csv.push(`"S2 Skills Notes",${s2SkillsNotes.join(',')},`);
  
  for (let b = 0; b < 6; b++) {
    const bandVals = [1, 2, 3].map(yrIdx => {
      const input = document.querySelector(`.band-input[data-band="${b}"][data-year-idx="${yrIdx}"]`);
      return input ? input.value : 0;
    });
    csv.push(`"S2 Band ${b} Count",${bandVals.join(',')},`);
  }
  csv.push('');

  const csvStr = csv.join('\n');
  const blob = new Blob(['\uFEFF' + csvStr], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', 'GVA_Scenario_Modeler_v3_Export.csv');
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

function handleImportClick() {
  document.getElementById('import-file-input').click();
}

function handleImportChange(e) {
  const file = e.target.files[0];
  if (!file) return;

  const reader = new FileReader();
  reader.onload = (evt) => {
    try {
      const contents = evt.target.result;
      const rows = parseCSV(contents);
      
      let inputsStartIdx = -1;
      for (let i = 0; i < rows.length; i++) {
        if (rows[i][0] && rows[i][0].trim() === 'Model Inputs') {
          inputsStartIdx = i;
          break;
        }
      }

      if (inputsStartIdx === -1) {
        alert('Could not find "Model Inputs" in the CSV. Please import a valid GVA Scenario Modeler CSV.');
        document.getElementById('import-file-input').value = '';
        return;
      }

      const params = {};
      for (let i = inputsStartIdx + 2; i < rows.length; i++) {
        const r = rows[i];
        if (!r || r.length === 0 || r[0] === '') break;
        const key = r[0].trim();
        const vals = r.slice(1);
        params[key] = vals;
      }

      const requiredKeys = [
        'Base Year', 'S1 Revenue', 'S2 Revenue', 
        'S1 Profit Margin %', 'S2 Profit Margin %', 
        'S1 Employee Count', 'Baseline Employee Cost', 'Project Cost', 
        'S2 Upskilled Count', 'S2 Skills Notes'
      ];
      for (const key of requiredKeys) {
        if (!params[key]) {
          alert(`Missing required parameter "${key}" in the CSV.`);
          document.getElementById('import-file-input').value = '';
          return;
        }
      }

      const importedBaseYear = parseInt(params['Base Year'][0]);
      if (!isNaN(importedBaseYear)) {
        updateBaseYear(importedBaseYear);
      }

      const s1Revs = params['S1 Revenue'].slice(0, 4).map(Number);
      const s2Revs = params['S2 Revenue'].slice(0, 4).map(Number);
      scenario1.setValues(s1Revs);
      scenario2.setValues(s2Revs);
      syncChartScales(s1Revs[0]);

      const s1Emps = params['S1 Employee Count'].slice(0, 4).map(Number);
      document.getElementById('emp1-baseline').value = s1Emps[0];
      document.getElementById('emp1-y1').value = s1Emps[1];
      document.getElementById('emp1-y2').value = s1Emps[2];
      document.getElementById('emp1-y3').value = s1Emps[3];

      document.getElementById('emp1-cost').value = Number(params['Baseline Employee Cost'][0]);

      document.getElementById('emp1-baseline').dispatchEvent(new Event('input'));
      document.getElementById('emp1-cost').dispatchEvent(new Event('input'));

      const upskilled = params['S2 Upskilled Count'].slice(0, 3).map(Number);
      document.getElementById('upskilled-y1').value = upskilled[0];
      document.getElementById('upskilled-y2').value = upskilled[1];
      document.getElementById('upskilled-y3').value = upskilled[2];

      const skillsNotes = params['S2 Skills Notes'].slice(0, 3);
      document.getElementById('skills-note-y1').value = skillsNotes[0] || '';
      document.getElementById('skills-note-y2').value = skillsNotes[1] || '';
      document.getElementById('skills-note-y3').value = skillsNotes[2] || '';

      for (let b = 0; b < 6; b++) {
        const key = `S2 Band ${b} Count`;
        if (params[key]) {
          const vals = params[key].slice(0, 3).map(Number);
          for (let yr = 1; yr <= 3; yr++) {
            const input = document.querySelector(`.band-input[data-band="${b}"][data-year-idx="${yr}"]`);
            if (input) {
              input.value = vals[yr - 1] || 0;
            }
          }
        }
      }

      updateEmployee2();

      const s1Margins = params['S1 Profit Margin %'].slice(0, 4).map(Number);
      const s2Margins = params['S2 Profit Margin %'].slice(0, 4).map(Number);
      for (let i = 0; i < 4; i++) {
        refreshProfit1.rawMargins[i] = s1Margins[i];
        refreshProfit2.rawMargins[i] = s2Margins[i];
      }

      refreshProfit1();
      refreshProfit2();

      const projectCost = Number(params['Project Cost'][0]);
      document.getElementById('project-cost-input').value = projectCost;

      updateSummaryTable();
      alert('Import completed successfully!');
    } catch (err) {
      console.error(err);
      alert('An error occurred while parsing the CSV: ' + err.message);
    }
    document.getElementById('import-file-input').value = '';
  };
  reader.readAsText(file);
}

function parseCSV(text) {
  const lines = [];
  let row = [""];
  let inQuotes = false;
  
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    const next = text[i+1];
    
    if (inQuotes) {
      if (c === '"') {
        if (next === '"') {
          row[row.length - 1] += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        row[row.length - 1] += c;
      }
    } else {
      if (c === '"') {
        inQuotes = true;
      } else if (c === ',') {
        row.push("");
      } else if (c === '\r' || c === '\n') {
        if (c === '\r' && next === '\n') {
          i++;
        }
        lines.push(row);
        row = [""];
      } else {
        row[row.length - 1] += c;
      }
    }
  }
  if (row.length > 1 || row[0] !== "") {
    lines.push(row);
  }
  return lines;
}

// Deferred Dashboard Initialization function
function initializeDashboard() {
  initializeDynamicHeaders();

  scenario1 = createScenarioChart({
    svgId: 'chart1',
    summaryId: 'summary1',
    title: 'Scenario 1',
    series: [
      { label: labels[0], value: 450 },
      { label: labels[1], value: 580 },
      { label: labels[2], value: 430 },
      { label: labels[3], value: 490 }
    ],
    onUpdate: (data) => {
      if (scenario2) {
        const currentS2Data = scenario2.getData();
        if (currentS2Data[0].value !== data[0].value) {
          scenario2.setDataValue(0, data[0].value);
          syncChartScales(data[0].value);
        }
      }
      refreshProfit1();
    }
  });

  scenario2 = createScenarioChart({
    svgId: 'chart2',
    summaryId: 'summary2',
    title: 'Scenario 2',
    series: [
      { label: labels[0], value: 450 },
      { label: labels[1], value: 460 },
      { label: labels[2], value: 600 },
      { label: labels[3], value: 500 }
    ],
    onUpdate: (data) => {
      if (scenario1) {
        const currentS1Data = scenario1.getData();
        if (currentS1Data[0].value !== data[0].value) {
          scenario1.setDataValue(0, data[0].value);
          syncChartScales(data[0].value);
        }
      }
      refreshProfit2();
    }
  });

  refreshProfit1 = createProfitControls({
    containerId: 'profitGrid1',
    scenarioKey: 's1',
    scenarioName: 'Scenario 1',
    defaultPercents: [10, 15, 20, 22],
    getScenarioData: scenario1.getData
  });

  refreshProfit2 = createProfitControls({
    containerId: 'profitGrid2',
    scenarioKey: 's2',
    scenarioName: 'Scenario 2',
    defaultPercents: [10, 16, 24, 28],
    getScenarioData: scenario2.getData
  });

  createEmployeeLogic('emp1', 's1');

  document.querySelectorAll('.band-input').forEach(input => {
    input.addEventListener('input', updateEmployee2);
  });
  ['1', '2', '3'].forEach(idx => {
    document.getElementById(`upskilled-y${idx}`).addEventListener('input', updateEmployee2);
    document.getElementById(`emp1-y${idx}`).addEventListener('input', () => syncCountToBands(idx));
    document.getElementById(`emp2-y${idx}`).addEventListener('input', () => syncCountToBands(idx));
  });
  document.getElementById('emp2-baseline').addEventListener('input', updateEmployee2);
  document.getElementById('emp2-cost').addEventListener('input', updateEmployee2);

  updateEmployee2();

  document.getElementById('profitGrid1-percent-input-0').addEventListener('input', syncProfitBaseline);
  const amt1 = document.getElementById('profitGrid1-amount-input-0');
  if (amt1) {
    amt1.addEventListener('input', () => {
      setTimeout(syncProfitBaseline, 0);
    });
  }

  document.getElementById('emp1-baseline').addEventListener('input', (e) => syncEmpBaseline(e, 'emp2-baseline'));
  document.getElementById('emp1-cost').addEventListener('input', (e) => syncEmpBaseline(e, 'emp2-cost'));

  const pcInput = document.getElementById('project-cost-input');
  if (pcInput) pcInput.addEventListener('input', updateSummaryTable);

  // Bind Export/Import
  document.getElementById('export-btn').addEventListener('click', handleExport);
  document.getElementById('import-btn').addEventListener('click', handleImportClick);
  document.getElementById('import-file-input').addEventListener('change', handleImportChange);

  // Bind Modal
  document.getElementById('modal-apply-btn').addEventListener('click', handleApplyBaseline);
  document.getElementById('modal-skip-btn').addEventListener('click', handleSkipBaseline);
  document.getElementById('edit-baseline-btn').addEventListener('click', showBaselineModal);

  scenario1.refresh();
  scenario2.refresh();
  syncChartScales(450);
  updateSummaryTable();

  const baselineInitialized = sessionStorage.getItem('gva_baseline_initialized') === 'true';
  if (!baselineInitialized) {
    setTimeout(showBaselineModal, 300);
  }
}

// Initialize Authentication Check
checkAuth();
